
@Echo Off

Set PWD=%cd%
Set "PWD=%PWD:\=/%"

Set "SQHOME=%HOMEPATH:\=/%"

Set SQOPTS=
Set EVARS=SQITCH_CONFIG SQITCH_USERNAME SQITCH_PASSWORD SQITCH_FULLNAME SQITCH_EMAIL SQITCH_TARGET
Set EVARS=%EVARS% PGUSER PGPASSWORD PGHOST PGHOSTADDR PGPORT PGDATABASE PGSERVICE PGOPTIONS PGSSLMODE PGREQUIRESSL
Set EVARS=%EVARS% PGSSLCOMPRESSION PGREQUIREPEER PGKRBSRVNAME PGKRBSRVNAME PGGSSLIB PGCONNECT_TIMEOUT PGCLIENTENCODING PGTARGETSESSIONATTRS

SetLocal EnableDelayedExpansion
FOR %%x in (%EVARS%) DO (
    If "!%%x!" neq "" (
        Set SQOPTS=%SQOPTS% -e %%x=!%%x!
    )
)

docker run -it --rm --network host %SQOPTS% -v "%PWD%":/repo:rw -v "%SQHOME%":/home:rw sqitch/sqitch %*

