[core]
	engine = pg
	# plan_file = sqitch.plan
	# top_dir = .

[engine "pg"]
	# target = db:pg:
	# registry = sqitch
	client = psql

[user]
    name = Johan von Boer
    email = johan.von.boer@umu.se

# [target "staging-test"]
# 	uri = db:pg://humlab_admin@humlabseadserv.srv.its.umu.se/sead_staging_test

# [target "staging-bugs"]
# 	uri = db:pg://humlab_admin@humlabseadserv.srv.its.umu.se/sead_staging_bugs

[target "local"]
	uri = db:pg://sead_master@localhost:5432/sead_staging

[target "staging"]
	uri = db:pg://humlab_admin@humlabseadserv.srv.its.umu.se:5433/sead_staging

[target "staging-dev"]
	uri = db:pg://humlab_admin@humlabseadserv.srv.its.umu.se:8089/sead_staging_test

[target "production"]
	uri = db:pg://humlab_admin@humlabseadserv.srv.its.umu.se:5432/sead_production
