-- Deploy sead_change_control:20191125_DML_CERAMICS_LOOKUP to pg

/****************************************************************************************************************
  Author        Roger Mähler
  Date          2019-01-01
  Description
  Prerequisites
  Reviewer
  Approver
  Idempotent    Yes
  Notes
*****************************************************************************************************************/

begin;
do $$
declare new_id int;
begin

    begin
        perform sead_utility.sync_sequence('public', 'tbl_locations');
        perform sead_utility.sync_sequence('public', 'tbl_methods');

        new_id = 3911;
        with new_locations (location_id, location_name, location_type_id) as (values
            (new_id + 0, 'Lund', 4)
			(new_id + 1, 'Aldenhovener Platte', 17)
			(new_id + 2, 'Attica', 2)
			(new_id + 3, 'Bagamoyo', 4)
			(new_id + 4, 'Bornholm', 18)
			(new_id + 5, 'Buhera', 2)
			(new_id + 6, 'Buskerud', 2)
			(new_id + 7, 'Chachapoyas', 2)
			(new_id + 8, 'Varsinais-Suomi', 14)
			(new_id + 9, 'Etruria', 14)
			(new_id + 10, 'Fyn', 18)
			(new_id + 11, 'Odense ', 14)
			(new_id + 12, 'Hedmark', 2)
			(new_id + 13, 'Hordaland', 2)
			(new_id + 14, 'Isle of Bazaruto', 18)
			(new_id + 15, 'Kisarawe', 2)
			(new_id + 16, 'Kurzeme', 14)
			(new_id + 17, 'Laconia', 7)
			(new_id + 18, 'Latium', 2)
			(new_id + 19, 'Limburg', 2)
			(new_id + 20, 'Lofoten', 7)
			(new_id + 21, 'Mazowieckie', 2)
			(new_id + 22, 'Mecklenburg-Vorpommern', 2)
			(new_id + 23, 'Möre og Romsdal', 2)
			(new_id + 24, 'New Ireland', 2)
			(new_id + 25, 'Nordland', 2)
			(new_id + 26, 'Nordrhein-Westfalen', 2)
			(new_id + 27, 'Nordrhein-Westfalen or Belgium', 7)
			(new_id + 28, 'Uusimaa', 2)
			(new_id + 29, 'Oost Flevoland', 14)
			(new_id + 30, 'Ostholstein', 2)
			(new_id + 31, 'Peloponnese', 2)
			(new_id + 32, 'Pomorskie', 2)
			(new_id + 33, 'Rheinland-Pfalz', 2)
			(new_id + 34, 'Rheinland', 7)
			(new_id + 35, 'Rogaland', 2)
			(new_id + 36, 'Saipan', 18)
			(new_id + 37, 'Sardegna', 2)
			(new_id + 38, 'Schleswig', 4)
			(new_id + 39, 'Schleswig-Holstein', 2)
			(new_id + 40, 'Sicilia', 2)
			(new_id + 41, 'Sjælland', 2)
			(new_id + 42, 'Wielkopolskie', 2)
			(new_id + 43, 'Wielkopolskie?', 2)
			(new_id + 44, 'Sunnmøre', 16)
			(new_id + 45, 'Sør-Varanger', 2)
			(new_id + 46, 'Hämeenlinna', 4)
			(new_id + 47, 'Telemark', 2)
			(new_id + 48, 'Toscana', 2)
			(new_id + 49, 'Toscana or Lazio', 7)
			(new_id + 50, 'Transilvania ', 16)
			(new_id + 51, 'Tucuman', 2)
			(new_id + 52, 'Oroolong', 18)
			(new_id + 53, 'Vest-Agder', 2)
			(new_id + 54, 'Vestmannaeyjar', 2)
			(new_id + 55, 'Viang chan', 4)
			(new_id + 56, 'Zachodniopomorskie', 2)
			(new_id + 57, 'Åland', 2)
			(new_id + 58, 'Östergötland', 2)
			(new_id + 59, 'Eastern Holland?', 16)
			(new_id + 60, 'Aakirkeby', 14)
			(new_id + 61, 'Adelsö socken', 2)
			(new_id + 62, 'Almby socken', 2)
			(new_id + 63, 'Alta', 2)
			(new_id + 64, 'Alunda socken', 2)
			(new_id + 65, 'Annelöv socken', 2)
			(new_id + 66, 'Aricia?', 2)
			(new_id + 67, 'Arjeplog socken', 2)
			(new_id + 68, 'Askeby socken', 2)
			(new_id + 69, 'Asmundtorp socken', 2)
			(new_id + 70, 'Augerum socken', 2)
			(new_id + 71, 'Barsebäck socken', 2)
			(new_id + 72, 'Bergen', 4)
			(new_id + 73, 'Bjäresjö socken', 2)
			(new_id + 74, 'Bjärtrå socken', 2)
			(new_id + 75, 'Björklinge socken', 2)
			(new_id + 76, 'Pori', 2)
			(new_id + 77, 'Blidsberg socken', 2)
			(new_id + 78, 'Blowatz', 2)
			(new_id + 79, 'Bodum socken', 2)
			(new_id + 80, 'Borgeby socken', 2)
			(new_id + 81, 'Borrby socken', 2)
			(new_id + 82, 'Botkyrka socken', 2)
			(new_id + 83, 'Bromölla ', 2)
			(new_id + 84, 'Brudager', 2)
			(new_id + 85, 'Brügge', 4)
			(new_id + 86, 'Brörup?', 2)
			(new_id + 87, 'Burlöv socken', 2)
			(new_id + 88, 'Bälinge socken', 2)
			(new_id + 89, 'Lambak ng Cagayan', 2)
			(new_id + 90, 'Carunia', 2)
			(new_id + 91, 'Chojna', 4)
			(new_id + 92, 'Cluj-Napoca', 2)
			(new_id + 93, 'Colalao del Valle', 4)
			(new_id + 94, 'Dagstorp socken', 2)
			(new_id + 95, 'Dalby socken', 2)
			(new_id + 96, 'Danmark socken', 2)
			(new_id + 97, 'Deset?', 4)
			(new_id + 98, 'Dronten', 2)
			(new_id + 99, 'Dunker socken', 2)
			(new_id + 100, 'Eggby & Öglunda', 7)
			(new_id + 101, 'Eidanger', 2)
			(new_id + 102, 'Ekeby socken', 2)
			(new_id + 103, 'Eker socken', 2)
			(new_id + 104, 'Ekerö socken', 2)
			(new_id + 105, 'Eksta socken', 2)
			(new_id + 106, 'Endre socken', 2)
			(new_id + 107, 'Enslöv socken', 2)
			(new_id + 108, 'Espe', 4)
			(new_id + 109, 'Eura', 2)
			(new_id + 110, 'Farsund', 2)
			(new_id + 111, 'Farum', 4)
			(new_id + 112, 'Fellingsbro socken', 2)
			(new_id + 113, 'Fjälkestad socken', 2)
			(new_id + 114, 'Fjälkinge socken', 2)
			(new_id + 115, 'Fjällsjö socken', 2)
			(new_id + 116, 'Flemlöse ', 2)
			(new_id + 117, 'Flädie socken', 2)
			(new_id + 118, 'Fosie socken', 2)
			(new_id + 119, 'Froland', 2)
			(new_id + 120, 'Fårö socken', 2)
			(new_id + 121, 'Gamla Uppsala socken', 2)
			(new_id + 122, 'Gdańsk', 4)
			(new_id + 123, 'Gevninge', 2)
			(new_id + 124, 'Giske', 2)
			(new_id + 125, 'Glanshammar socken', 2)
			(new_id + 126, 'Glemminge socken', 2)
			(new_id + 127, 'Glesborg ', 2)
			(new_id + 128, 'Glostorp socken', 2)
			(new_id + 129, 'Glostrup ', 2)
			(new_id + 130, 'Glumslöv socken', 2)
			(new_id + 131, 'Grajewo', 4)
			(new_id + 132, 'Gransherad', 14)
			(new_id + 133, 'Grevie socken', 2)
			(new_id + 134, 'Grimeton socken', 2)
			(new_id + 135, 'Grimstad', 2)
			(new_id + 136, 'Grobina', 4)
			(new_id + 137, 'Grosssolt', 2)
			(new_id + 138, 'Grube', 2)
			(new_id + 139, 'Gräsgård socken', 2)
			(new_id + 140, 'Grödinge socken', 2)
			(new_id + 141, 'Grötlingbo socken', 2)
			(new_id + 142, 'Gualöv socken', 2)
			(new_id + 143, 'Gudbjerg ', 2)
			(new_id + 144, 'Gudme ', 2)
			(new_id + 145, 'Gudme-Lundeborg', 7)
			(new_id + 146, 'Gödelöv socken', 2)
			(new_id + 147, 'Gödestad socken', 2)
			(new_id + 148, 'Gökhem socken', 2)
			(new_id + 149, 'Haarlem', 2)
			(new_id + 150, 'Hablingbo socken', 2)
			(new_id + 151, 'Halmstad socken', 2)
			(new_id + 152, 'Hangvar socken', 2)
			(new_id + 153, 'Haram', 2)
			(new_id + 154, 'Harbo socken', 2)
			(new_id + 155, 'Harplinge socken', 2)
			(new_id + 156, 'Hasslösa socken', 2)
			(new_id + 157, 'Hauho', 14)
			(new_id + 158, 'Heddal', 4)
			(new_id + 159, 'Hedeskoga socken', 2)
			(new_id + 160, 'Heimaey', 18)
			(new_id + 161, 'Hellum ', 2)
			(new_id + 162, 'Helsingborg socken', 2)
			(new_id + 163, 'Helsinge ', 2)
			(new_id + 164, 'Hemse socken', 2)
			(new_id + 165, 'Hillerslev ', 2)
			(new_id + 166, 'Stevns', 2)
			(new_id + 167, 'Holmedal socken', 2)
			(new_id + 168, 'Horne ', 2)
			(new_id + 169, 'Hossmo socken', 2)
			(new_id + 170, 'Hubbo socken', 2)
			(new_id + 171, 'Hulterstad socken', 2)
			(new_id + 172, 'Hylke ', 2)
			(new_id + 173, 'Hyllie socken', 2)
			(new_id + 174, 'Häverö socken', 2)
			(new_id + 175, 'Ingelstorp socken', 2)
			(new_id + 176, 'Ivetofta socken', 2)
			(new_id + 177, 'Jonstorp socken', 2)
			(new_id + 178, 'Järrestad socken', 2)
			(new_id + 179, 'Jörn socken', 2)
			(new_id + 180, 'Kalanti', 14)
			(new_id + 181, 'Karaby socken', 2)
			(new_id + 182, 'Karlskrona', 4)
			(new_id + 183, 'Kiel', 4)
			(new_id + 184, 'Kil socken', 2)
			(new_id + 185, 'Kila socken', 2)
			(new_id + 186, 'Kirke Saaby ', 2)
			(new_id + 187, 'Kjula socken', 2)
			(new_id + 188, 'Klemensker ', 2)
			(new_id + 189, 'Kornerup ', 2)
			(new_id + 190, 'Kortrijk', 2)
			(new_id + 191, 'Kosel', 2)
			(new_id + 192, 'Düren', 4)
			(new_id + 193, 'Schleswig-Flensburg', 2)
			(new_id + 194, 'Kragelund ', 2)
			(new_id + 195, 'Kragerø? ', 2)
			(new_id + 196, 'Kristiansand?', 2)
			(new_id + 197, 'Krokek socken', 2)
			(new_id + 198, 'Kungsbacka ', 2)
			(new_id + 199, 'Kungsör', 2)
			(new_id + 200, 'Kvarsebo socken', 2)
			(new_id + 201, 'Kvillinge socken', 2)
			(new_id + 202, 'Kvistofta socken', 2)
			(new_id + 203, 'Kymi', 14)
			(new_id + 204, 'Kyrkheddinge socken', 2)
			(new_id + 205, 'Källstad socken', 2)
			(new_id + 206, 'Kökar', 2)
			(new_id + 207, 'Köping socken', 2)
			(new_id + 208, 'Laitila', 4)
			(new_id + 209, 'Landskrona ', 4)
			(new_id + 210, 'Lieto', 2)
			(new_id + 211, 'Lilla Beddinge socken', 2)
			(new_id + 212, 'Lilla Malma socken', 2)
			(new_id + 213, 'Lilla Slågarp & Västra Alstad', 7)
			(new_id + 214, 'Linköping ', 4)
			(new_id + 215, 'Litslena socken', 2)
			(new_id + 216, 'Ljung socken', 2)
			(new_id + 217, 'Ljungby socken', 2)
			(new_id + 218, 'Los socken', 2)
			(new_id + 219, 'Lund socken', 2)
			(new_id + 220, 'Lunda socken', 2)
			(new_id + 221, 'Löddeköpinge socken', 2)
			(new_id + 222, 'Löderup socken', 2)
			(new_id + 223, 'Lövånger socken', 2)
			(new_id + 224, 'Maglarp socken', 2)
			(new_id + 225, 'Maharashtra', 2)
			(new_id + 226, 'Malling ', 2)
			(new_id + 227, 'Markaryd socken', 2)
			(new_id + 228, 'Mellby socken', 2)
			(new_id + 229, 'Meløy', 2)
			(new_id + 230, 'Mjällby socken', 2)
			(new_id + 231, 'Murlo', 2)
			(new_id + 232, 'Nyker ', 2)
			(new_id + 233, 'Neufvilles', 4)
			(new_id + 234, 'Norra Nöbbelöv socken', 2)
			(new_id + 235, 'Norrvidinge socken', 2)
			(new_id + 236, 'Nosaby or Fjälkinge', 7)
			(new_id + 237, 'Nousiainen', 2)
			(new_id + 238, 'Novgorod', 4)
			(new_id + 239, 'Nylars?', 4)
			(new_id + 240, 'Näs socken?', 2)
			(new_id + 241, 'Nöbbele socken', 2)
			(new_id + 242, 'Oure ', 2)
			(new_id + 243, 'Oxie socken', 2)
			(new_id + 244, 'Paattinen', 4)
			(new_id + 245, 'Partille socken', 2)
			(new_id + 246, 'Porvoo', 4)
			(new_id + 247, 'Resmo socken', 2)
			(new_id + 248, 'Revsund socken', 2)
			(new_id + 249, 'Ringerike', 2)
			(new_id + 250, 'Riseberga socken', 2)
			(new_id + 251, 'Romfartuna socken', 2)
			(new_id + 252, 'Rovaniemi', 2)
			(new_id + 253, 'Rångedala socken', 2)
			(new_id + 254, 'Rörum socken', 2)
			(new_id + 255, 'Saksild ', 2)
			(new_id + 256, 'Salaj', 2)
			(new_id + 257, 'Salem socken', 2)
			(new_id + 258, 'Saltvik', 2)
			(new_id + 259, 'Sande', 2)
			(new_id + 260, 'Sandseryd socken', 2)
			(new_id + 261, 'Saxtorp socken', 2)
			(new_id + 262, 'Sebber ', 2)
			(new_id + 263, 'Segeberg', 2)
			(new_id + 264, 'Segerstad socken', 2)
			(new_id + 265, 'Sigtuna ', 4)
			(new_id + 266, 'Silbodal socken', 2)
			(new_id + 267, 'Silte socken', 2)
			(new_id + 268, 'Sjonhem socken', 2)
			(new_id + 269, 'Själevad socken', 2)
			(new_id + 270, 'Skara socken', 2)
			(new_id + 271, 'Skjerstad ', 16)
			(new_id + 272, 'Skummeslöv socken', 2)
			(new_id + 273, 'Skuttunge socken', 2)
			(new_id + 274, 'Skållerud socken', 2)
			(new_id + 275, 'Skånes-Fagerhult socken', 2)
			(new_id + 276, 'Skänninge ', 4)
			(new_id + 277, 'Skärv socken', 2)
			(new_id + 278, 'Sligeach', 2)
			(new_id + 279, 'Snöstorp socken', 2)
			(new_id + 280, 'Sortland ', 2)
			(new_id + 281, 'Stora Malm socken', 2)
			(new_id + 282, 'Uppåkra socken', 2)
			(new_id + 283, 'Stenkyrka socken', 2)
			(new_id + 284, 'Stenungsund?', 2)
			(new_id + 285, 'Stockholm', 4)
			(new_id + 286, 'Mora socken', 2)
			(new_id + 287, 'Stora Herrestad socken', 2)
			(new_id + 288, 'Stora Köpinge socken', 2)
			(new_id + 289, 'Stora Åby socken', 2)
			(new_id + 290, 'Stävie socken', 2)
			(new_id + 291, 'Sula', 2)
			(new_id + 292, 'Säby socken', 2)
			(new_id + 293, 'Sävare socken', 2)
			(new_id + 294, 'Söderköping ', 4)
			(new_id + 295, 'Södertälje ', 4)
			(new_id + 296, 'Söderåkra socken', 2)
			(new_id + 297, 'Södra Åkarp socken', 2)
			(new_id + 298, 'Sölvesborg socken', 2)
			(new_id + 299, 'Sövde socken', 2)
			(new_id + 300, 'Tensta socken', 2)
			(new_id + 301, 'Thorsager', 2)
			(new_id + 302, 'Tierp socken', 2)
			(new_id + 303, 'Tofta socken', 2)
			(new_id + 304, 'Torbjörntorp socken', 2)
			(new_id + 305, 'Torhamn socken', 2)
			(new_id + 306, 'Torridal', 16)
			(new_id + 307, 'Tortuna socken', 2)
			(new_id + 308, 'Træna', 2)
			(new_id + 309, 'Trelleborg socken', 2)
			(new_id + 310, 'Trolle-Ljungby socken', 2)
			(new_id + 311, 'Trosa socken', 2)
			(new_id + 312, 'Tullstorp socken', 2)
			(new_id + 313, 'Tumbo socken', 2)
			(new_id + 314, 'Tvedestrand', 2)
			(new_id + 315, 'Tveta socken', 2)
			(new_id + 316, 'Tystberga socken', 2)
			(new_id + 317, 'Tåby socken', 2)
			(new_id + 318, 'Tårnborg ', 2)
			(new_id + 319, 'Täby socken', 2)
			(new_id + 320, 'Tønsberg', 2)
			(new_id + 321, 'Törnevalla socken', 2)
			(new_id + 322, 'Uppsala ', 4)
			(new_id + 323, 'Vadstena ', 4)
			(new_id + 324, 'Værøy', 2)
			(new_id + 325, 'Vagnhärad socken', 2)
			(new_id + 326, 'Valby', 4)
			(new_id + 327, 'Vallby socken', 2)
			(new_id + 328, 'Valleberga socken', 2)
			(new_id + 329, 'Valtorp socken', 2)
			(new_id + 330, 'Vansö socken', 2)
			(new_id + 331, 'Warszawa', 4)
			(new_id + 332, 'Vendel socken', 2)
			(new_id + 333, 'Ventlinge socken', 2)
			(new_id + 334, 'Vesterøya', 16)
			(new_id + 335, 'Vestvågöy ', 2)
			(new_id + 336, 'Veta socken', 2)
			(new_id + 337, 'Viksta socken', 2)
			(new_id + 338, 'Villberga socken', 2)
			(new_id + 339, 'Vintrosa socken', 2)
			(new_id + 340, 'Visby socken', 2)
			(new_id + 341, 'Vreta Kloster socken', 2)
			(new_id + 342, 'Vågsöy', 2)
			(new_id + 343, 'Vårdsberg & Linköping', 7)
			(new_id + 344, 'Vårfrukyrka socken', 2)
			(new_id + 345, 'Väderstad socken', 2)
			(new_id + 346, 'Väse socken', 2)
			(new_id + 347, 'Västergarn socken', 2)
			(new_id + 348, 'Västerljung socken', 2)
			(new_id + 349, 'Västerås', 4)
			(new_id + 350, 'Badelunda socken', 2)
			(new_id + 351, 'Västra Karaby socken', 2)
			(new_id + 352, 'Västra Tollstad socken', 2)
			(new_id + 353, 'Väte socken', 2)
			(new_id + 354, 'Ystad ', 4)
			(new_id + 355, 'Å socken', 2)
			(new_id + 356, 'Ådals-Liden socken', 2)
			(new_id + 357, 'Åhus socken', 2)
			(new_id + 358, 'Ål socken', 2)
			(new_id + 359, 'Ås socken', 2)
			(new_id + 360, 'Flensburg', 4)
			(new_id + 361, 'Älgarås socken', 2)
			(new_id + 362, 'Ärentuna socken', 2)
			(new_id + 363, 'Öggestorp socken', 2)
			(new_id + 364, 'Öja socken', 2)
			(new_id + 365, 'Örkelljunga socken', 2)
			(new_id + 366, 'Ösmo socken', 2)
			(new_id + 367, 'Östra Eneby socken', 2)
			(new_id + 368, 'Övergran socken', 2)
			(new_id + 369, 'Överjärna socken', 2)
			(new_id + 370, 'Germany/Belgium?', 1)
        ) insert into tbl_locations (location_id, location_name, location_type_id)
        select a.location_id, a.location_name, a.location_type_id
        from new_locations a;

        new_id =  70;
        with new_methods (method_id, biblio_id, description, method_abbrev_or_alt_name, method_group_id, method_name, record_type_id, unit_id) as (values
			(new_id + 0, NULL, 'A piece of the ceramic sherd is cut off, fastened to a microscope slide, ground down to 0,03 mm, and polished. The tempering grains and clay is then studied under a microscope to determine clay content, fraction size, sorting and tempering content. These are all determined ocularly. The max grain size and total percent tempering is determined by marking the tempering grains in a photograph projected from the camera connected to the microscope and calculating in the program.', 'Petrographic', 9, 'Petrographic microscopy', NULL, NULL)
			(new_id + 1, NULL, 'A raw clay sample and a sample of the ceramic sherd, or archaeological sample, is heated in a lab oven in 100 °C intervals, for a total of 30 minutes, up to 1000 °C. The colour change during and after heating is noted and compared to the Munsell Colour Chart to determine the firing temperature and firing atmosphere of the archaeological sample. The samples are then once more heated above 1000 °C, in 50 °C intervals, until they reach their melting point. The assumption for the thermal analysis is that the colour change of the ceramic sample doesn''t occur until after the original firing temperature has been reached.', 'Thermal', 9, 'Thermal analysis', NULL, NULL)
			(new_id + 2, NULL, 'Collection of ceramic samples by unspecified means', 'Ceramics', 13, 'Ceramics collection', NULL, NULL)

        select a.method_id, a.biblio_id, a.description, a.method_abbrev_or_alt_name, a.method_group_id, a.method_name, a.record_type_id, a.unit_id
        from new_methods a;

        perform sead_utility.sync_sequence('public', 'tbl_locations');
        perform sead_utility.sync_sequence('public', 'tbl_methods');

    exception when sqlstate 'GUARD' then
        raise notice 'ALREADY EXECUTED';
    end;

end $$;
commit;