COMMENT ON COLUMN "public"."tbl_abundance_elements"."record_type_id" IS 'used to restrict list of available elements according to record type. enables specific use of single term for multiple proxies whilst avoiding confusion, e.g. mni insects, mni seeds';
COMMENT ON COLUMN "public"."tbl_abundance_elements"."element_name" IS 'short name for element, e.g. mni, seed, leaf';
COMMENT ON COLUMN "public"."tbl_abundance_elements"."element_description" IS 'explanation of short name, e.g. minimum number of individuals, base of seed grain, covering of leaf or flower bud';
COMMENT ON COLUMN "public"."tbl_abundances"."abundance_element_id" IS 'allows recording of different parts for single taxon, e.g. leaf, seed, mni etc.';
COMMENT ON COLUMN "public"."tbl_abundances"."abundance" IS 'usually count value (abundance) but can be presence (1) or catagorical or relative scale, as defined by tbl_data_types through tbl_datasets';
COMMENT ON TABLE "public"."tbl_abundances" IS '20120503pib deleted column "abundance_modification_id" as appeared superfluous with "abundance_id" in tbl_adbundance_modifications';
COMMENT ON COLUMN "public"."tbl_aggregate_datasets"."aggregate_dataset_name" IS 'name of aggregated dataset';
COMMENT ON COLUMN "public"."tbl_aggregate_datasets"."description" IS 'Notes explaining the purpose of the aggregated set of analysis entities';
COMMENT ON COLUMN "public"."tbl_aggregate_order_types"."aggregate_order_type" IS 'aggregate order name, e.g. site name, age, sample depth, altitude';
COMMENT ON COLUMN "public"."tbl_aggregate_order_types"."description" IS 'explanation of ordering system';
COMMENT ON TABLE "public"."tbl_aggregate_order_types" IS '20120504pib: drop this? or replace with alternative?';
COMMENT ON COLUMN "public"."tbl_aggregate_samples"."aggregate_sample_name" IS 'optional name for aggregated entity.';
COMMENT ON TABLE "public"."tbl_aggregate_samples" IS '20120504pib: can we drop aggregate sample name? seems excessive and unnecessary sample names can be traced.';
COMMENT ON TABLE "public"."tbl_analysis_entities" IS '20120503pib deleted column preparation_method_id, but may need to cater for this in datasets...
20120506pib: deleted method_id and added table for multiple methods per entity';
COMMENT ON TABLE "public"."tbl_analysis_entity_ages" IS '20120504pib: should this be connected to physical sample instead of analysis entities? allowing multiple ages (from multiple dates) for a sample. at the moment it requires a lot of backtracing to find a sample''s age... but then again, it allows... what, exactly?';
COMMENT ON COLUMN "public"."tbl_analysis_entity_prep_methods"."method_id" IS 'preparation methods only';
COMMENT ON TABLE "public"."tbl_analysis_entity_prep_methods" IS '20120506pib: created to cater for multiple preparation methods for analysis but maintaining simple dataset concept.';
COMMENT ON TABLE "public"."tbl_ceramics_measurements" IS 'Type=lookup';
COMMENT ON TABLE "public"."tbl_chronologies" IS '20120504pib: note that the dropped age type recorded the type of dates (c14 etc) used in constructing the chronology... but is only one per chonology enough? can a chronology not be made up of mulitple types of age?';
COMMENT ON COLUMN "public"."tbl_dataset_masters"."biblio_id" IS 'primary reference for master dataset if available, e.g. buckland & buckland 2006 for bugscep';
COMMENT ON COLUMN "public"."tbl_dataset_masters"."master_name" IS 'identification of master dataset, e.g. mal, bugscep, dendrolab';
COMMENT ON COLUMN "public"."tbl_dataset_masters"."master_notes" IS 'description of master dataset, its form (e.g. database, lab) and any other relevant information for tracing it.';
COMMENT ON COLUMN "public"."tbl_dataset_masters"."url" IS 'website or other url for master dataset, be it a project, lab or... other';
COMMENT ON COLUMN "public"."tbl_dataset_submission_types"."submission_type" IS 'descriptive name for type of submission, e.g. original submission, ingestion from another database';
COMMENT ON COLUMN "public"."tbl_dataset_submission_types"."description" IS 'explanation of submission type, explaining clearly data ingestion mechanism';
COMMENT ON COLUMN "public"."tbl_dataset_submissions"."notes" IS 'any details of submission not covered by submission_type information, such as name of source from which submission originates if not covered elsewhere in database, e.g. from bugscep';
COMMENT ON COLUMN "public"."tbl_datasets"."dataset_name" IS 'something uniquely identifying the dataset for this site. may be same as sample group name, or created adhoc if necessary, but preferably with some meaning.';
COMMENT ON COLUMN "public"."tbl_dating_labs"."contact_id" IS 'address details are stored in tbl_contacts';
COMMENT ON COLUMN "public"."tbl_dating_labs"."international_lab_id" IS 'international standard radiocarbon lab identifier.
from http://www.radiocarbon.org/info/labcodes.html';
COMMENT ON COLUMN "public"."tbl_dating_labs"."lab_name" IS 'international standard name of radiocarbon lab, from http://www.radiocarbon.org/info/labcodes.html';
COMMENT ON TABLE "public"."tbl_dating_labs" IS '20120504pib: reduced this table and linked to tbl_contacts for address related data';
COMMENT ON TABLE "public"."tbl_dating_material" IS '20130722PIB: Added field date_updated';
COMMENT ON TABLE "public"."tbl_dendro_dates" IS '20130722PIB: Added field dating_uncertainty_id to cater for >< etc.
20130722PIB: prefixed fieldnames age_younger and age_older with "cal_" to conform with equivalent names in other tables';
COMMENT ON TABLE "public"."tbl_dendro_measurements" IS 'Type=lookup';
COMMENT ON COLUMN "public"."tbl_dimensions"."method_group_id" IS 'Limits choice of dimension by method group (e.g. size measurements, coordinate systems)';
COMMENT ON COLUMN "public"."tbl_features"."feature_name" IS 'estabilished reference name/number for the feature (note: not the sample). e.g. well 47, anl.3, c107.
remember that a sample can come from multiple features (e.g. c107 in well 47) but each feature should have a separate record.';
COMMENT ON COLUMN "public"."tbl_features"."feature_description" IS 'description of the feature. may include any field notes, lab notes or interpretation information useful for interpreting the sample data.';
COMMENT ON COLUMN "public"."tbl_geochron_refs"."biblio_id" IS 'reference for specific date';
COMMENT ON COLUMN "public"."tbl_geochronology"."age" IS 'radiocarbon (or other radiometric) age.';
COMMENT ON COLUMN "public"."tbl_geochronology"."error_older" IS 'plus (+) side of the measured error (set same as error_younger if standard +/- error)';
COMMENT ON COLUMN "public"."tbl_geochronology"."error_younger" IS 'minus (-) side of the measured error (set same as error_younger if standard +/- error)';
COMMENT ON COLUMN "public"."tbl_geochronology"."delta_13c" IS 'delta 13c where available for calibration correction.';
COMMENT ON COLUMN "public"."tbl_geochronology"."notes" IS 'notes specific to this date';
COMMENT ON TABLE "public"."tbl_geochronology" IS '20130722PIB: Altered field uncertainty (varchar) to dating_uncertainty_id and linked to tbl_dating_uncertainty to enable lookup of uncertainty modifiers for dates';
COMMENT ON COLUMN "public"."tbl_locations"."default_lat_dd" IS 'default latitude in decimal degrees for location, e.g. mid point of country. leave empty if not known.';
COMMENT ON COLUMN "public"."tbl_locations"."default_long_dd" IS 'default longitude in decimal degrees for location, e.g. mid point of country';
COMMENT ON COLUMN "public"."tbl_modification_types"."modification_type_name" IS 'short name of modification, e.g. carbonised';
COMMENT ON COLUMN "public"."tbl_modification_types"."modification_type_description" IS 'clear explanation of modification so that name makes sense to non-domain scientists';
COMMENT ON COLUMN "public"."tbl_physical_samples"."alt_ref_type_id" IS 'type of name represented by primary sample name, e.g. lab number, museum number etc.';
COMMENT ON COLUMN "public"."tbl_physical_samples"."sample_type_id" IS 'physical form of sample, e.g. bulk sample, kubienta subsample, core subsample, dendro core, dendro slice...';
COMMENT ON COLUMN "public"."tbl_physical_samples"."sample_name" IS 'reference number or name of sample. multiple references/names can be added as alternative references.';
COMMENT ON COLUMN "public"."tbl_physical_samples"."date_sampled" IS 'Date samples were taken. ';
COMMENT ON TABLE "public"."tbl_physical_samples" IS '20120504PIB: deleted columns XYZ and created external tbl_sample_coodinates
20120506PIB: deleted columns depth_top & depth_bottom and moved to tbl_sample_dimensions
20130416PIB: changed to date_sampled from date to varchar format to increase flexibility';
COMMENT ON COLUMN "public"."tbl_project_stages"."stage_name" IS 'stage of project in investigative cycle, e.g. desktop study, prospection, final excavation';
COMMENT ON COLUMN "public"."tbl_project_stages"."description" IS 'explanation of stage name term, including details of purpose and general contents';
COMMENT ON COLUMN "public"."tbl_project_types"."project_type_name" IS 'descriptive name for project type, e.g. consultancy, research, teaching; also combinations consultancy/teaching';
COMMENT ON COLUMN "public"."tbl_project_types"."description" IS 'project type combinations can be used where appropriate, e.g. teaching/research';
COMMENT ON COLUMN "public"."tbl_projects"."project_name" IS 'name of project (e.g. phil''s phd thesis, malmö ringroad vägverket)';
COMMENT ON COLUMN "public"."tbl_projects"."project_abbrev_name" IS 'optional. abbreviation of project name or acronym (e.g. vgv, swedab)';
COMMENT ON COLUMN "public"."tbl_projects"."description" IS 'brief description of project and any useful information for finding out more.';
COMMENT ON COLUMN "public"."tbl_radiocarbon_calibration"."c14_yr_bp" IS 'mid-point of c14 age.';
COMMENT ON COLUMN "public"."tbl_radiocarbon_calibration"."cal_yr_bp" IS 'mid-point of calibrated age.';
COMMENT ON COLUMN "public"."tbl_rdb"."location_id" IS 'geographical source/relevance of the specific code. e.g. the international iucn classification of species in the uk.';
COMMENT ON COLUMN "public"."tbl_rdb_systems"."location_id" IS 'geaographical relevance of rdb code system, e.g. uk, international, new forest';
COMMENT ON COLUMN "public"."tbl_record_types"."record_type_name" IS 'short name of proxy/proxies in group';
COMMENT ON COLUMN "public"."tbl_record_types"."record_type_description" IS 'detailed description of group and explanation for grouping';
COMMENT ON TABLE "public"."tbl_record_types" IS 'may also use this to group methods - e.g. phosphate analyses (whereas tbl_method_groups would store the larger group "palaeo chemical/physical" methods)';
COMMENT ON COLUMN "public"."tbl_relative_age_types"."age_type" IS 'name of chronological age type, e.g. archaeological period, single calendar date, calendar age range, blytt-sernander';
COMMENT ON COLUMN "public"."tbl_relative_age_types"."description" IS 'description of chronological age type, e.g. period defined by archaeological and or geological dates representing cultural activity period, climate period defined by palaeo-vegetation records';
COMMENT ON TABLE "public"."tbl_relative_age_types" IS '20130723PIB: replaced date_updated column with new one with same name but correct data type
20140226EE: replaced date_updated column with correct time data type';
COMMENT ON COLUMN "public"."tbl_relative_ages"."relative_age_name" IS 'name of the dating period, e.g. bronze age. calendar ages should be given appropriate names such as ad 1492, 74 bc';
COMMENT ON COLUMN "public"."tbl_relative_ages"."description" IS 'a description of the (usually) period.';
COMMENT ON COLUMN "public"."tbl_relative_ages"."c14_age_older" IS 'c14 age of younger boundary of period (where relevant).';
COMMENT ON COLUMN "public"."tbl_relative_ages"."c14_age_younger" IS 'c14 age of later boundary of period (where relevant). leave blank for calendar ages.';
COMMENT ON COLUMN "public"."tbl_relative_ages"."cal_age_older" IS '(approximate) age before present (1950) of earliest boundary of period. or if calendar age then the calendar age converted to bp.';
COMMENT ON COLUMN "public"."tbl_relative_ages"."cal_age_younger" IS '(approximate) age before present (1950) of latest boundary of period. or if calendar age then the calendar age converted to bp.';
COMMENT ON COLUMN "public"."tbl_relative_ages"."notes" IS 'any further notes not included in the description, such as reliability of definition or fuzzyness of boundaries.';
COMMENT ON COLUMN "public"."tbl_relative_ages"."abbreviation" IS 'Standard abbreviated form of name if available';
COMMENT ON TABLE "public"."tbl_relative_ages" IS '20120504PIB: removed biblio_id as is replaced by tbl_relative_age_refs
20130722PIB: changed colour in model to AliceBlue to reflect degree of user addition possible (i.e. ages can be added for reference in tbl_relative_dates)';
COMMENT ON COLUMN "public"."tbl_relative_dates"."method_id" IS 'dating method used to attribute sample to period or calendar date.';
COMMENT ON COLUMN "public"."tbl_relative_dates"."notes" IS 'any notes specific to the dating of this sample to this calendar or period based age';
COMMENT ON TABLE "public"."tbl_relative_dates" IS '20120504PIB: Added method_id to store dating method used to attribute sample to period or calendar date (e.g. strategraphic dating, typological)
20130722PIB: addded field dating_uncertainty_id to cater for "from", "to" and "ca." etc. especially from import of BugsCEP';
COMMENT ON COLUMN "public"."tbl_sample_coordinates"."accuracy" IS 'GPS type accuracy, e.g. 5m 10m 0.01m';
COMMENT ON COLUMN "public"."tbl_sample_dimensions"."dimension_id" IS 'details of the dimension measured';
COMMENT ON COLUMN "public"."tbl_sample_dimensions"."method_id" IS 'method describing dimension measurement, with link to units used';
COMMENT ON COLUMN "public"."tbl_sample_dimensions"."dimension_value" IS 'numerical value of dimension, in the units indicated in the documentation and interface.';
COMMENT ON TABLE "public"."tbl_sample_dimensions" IS '20120506pib: depth measurements for samples moved here from tbl_physical_samples';
COMMENT ON COLUMN "public"."tbl_sample_group_sampling_contexts"."sampling_context" IS 'short but meaningful name defining sample group context, e.g. stratigraphic sequence, archaeological excavation';
COMMENT ON COLUMN "public"."tbl_sample_group_sampling_contexts"."description" IS 'full explanation of the grouping term';
COMMENT ON COLUMN "public"."tbl_sample_group_sampling_contexts"."sort_order" IS 'allows lists to group similar or associated group context close to each other, e.g. modern investigations together, palaeo investigations together';
COMMENT ON TABLE "public"."tbl_sample_group_sampling_contexts" IS 'Type=lookup';
COMMENT ON COLUMN "public"."tbl_sample_groups"."method_id" IS 'sampling method, e.g. russian auger core, pitfall traps. note different from context in that it is specific to method of sample retrieval and not type of investigation.';
COMMENT ON COLUMN "public"."tbl_sample_groups"."sample_group_name" IS 'Name which identifies the collection of samples. For ceramics, use vessel number.';
COMMENT ON COLUMN "public"."tbl_sample_notes"."note_type" IS 'origin of the note, e.g. field note, lab note';
COMMENT ON COLUMN "public"."tbl_sample_notes"."note" IS 'note contents';
COMMENT ON COLUMN "public"."tbl_site_natgridrefs"."method_id" IS 'points to coordinate system.';
COMMENT ON TABLE "public"."tbl_site_natgridrefs" IS '20120507pib: removed tbl_national_grids and trasfered storage of coordinate systems to tbl_methods';
COMMENT ON COLUMN "public"."tbl_site_other_records"."biblio_id" IS 'reference to publication containing data';
COMMENT ON COLUMN "public"."tbl_site_other_records"."record_type_id" IS 'reference to type of data (proxy)';
COMMENT ON COLUMN "public"."tbl_site_preservation_status"."site_id" IS 'allows multiple preservation/threat records per site';
COMMENT ON COLUMN "public"."tbl_site_preservation_status"."preservation_status_or_threat" IS 'descriptive name for:
preservation status, e.g. (e.g. lost, damaged, threatened) or
main reason for potential or real risk to site (e.g. hydroelectric, oil exploitation, mining, forestry, climate change, erosion)';
COMMENT ON COLUMN "public"."tbl_site_preservation_status"."description" IS 'brief description of site preservation status or threat to site preservation. include data here that does not fit in the other fields (for now - we may expand these features later if demand exists)';
COMMENT ON COLUMN "public"."tbl_site_preservation_status"."assessment_type" IS 'type of assessment giving information on preservation status and threat, e.g. unesco report, archaeological survey';
COMMENT ON COLUMN "public"."tbl_site_preservation_status"."assessment_author_contact_id" IS 'person or authority in tbl_contacts responsible for the assessment of preservation status and threat';
COMMENT ON COLUMN "public"."tbl_site_preservation_status"."Evaluation_date" IS 'Date of assessment, either formal or informal';
COMMENT ON COLUMN "public"."tbl_species_associations"."associated_taxon_id" IS 'Taxon with which the primary taxon (taxon_id) is associated. ';
COMMENT ON COLUMN "public"."tbl_species_associations"."biblio_id" IS 'Reference where relationship between taxa is described or mentioned';
COMMENT ON COLUMN "public"."tbl_species_associations"."taxon_id" IS 'Primary taxon in relationship, i.e. this taxon has x relationship with the associated taxon';
COMMENT ON COLUMN "public"."tbl_species_associations"."association_type_id" IS 'Type of association between primary taxon (taxon_id) and associated taxon. Note that the direction of the association is important in most cases (e.g. x predates on y)';
COMMENT ON TABLE "public"."tbl_taxa_images" IS '20140226EE: changed the data type for date_updated';
COMMENT ON TABLE "public"."tbl_taxa_reference_specimens" IS '20140226EE: changed date_updated to correct data type';
COMMENT ON COLUMN "public"."tbl_taxa_seasonality"."location_id" IS 'geographical relevance of seasonality data';
COMMENT ON COLUMN "public"."tbl_taxa_synonyms"."notes" IS 'Any information useful to the history or usage of the synonym.';
COMMENT ON COLUMN "public"."tbl_taxa_synonyms"."synonym" IS 'Synonym at level defined by id level. I.e. if synonym is at genus level, then only the genus synonym is included here. Another synonym record is used for the species level synonym for the same taxon only if the name is different to that used in the master list.';
COMMENT ON COLUMN "public"."tbl_taxa_synonyms"."reference_type" IS 'Form of information relating to the synonym in the given bibliographic link, e.g. by use, definition, incorrect usage.';
COMMENT ON TABLE "public"."tbl_taxa_tree_master" IS '20130416PIB: removed default=0 for author_id and genus_id as was incorrect';
COMMENT ON TABLE "public"."tbl_tephra_dates" IS '20130722PIB: Added field dating_uncertainty_id to cater for >< etc.';