-- Deploy sead_api:20190101_DML_FACET_SCHEMA to pg

/****************************************************************************************************************
  Author        Roger Mähler
  Date          2019-01-01
  Description
  Reviewer
  Approver
  Idempotent    Yes
  Notes
*****************************************************************************************************************/

begin;
do $$
begin

    begin

        set role querysead_owner;

        set search_path = facet, pg_catalog;
        set default_with_oids = false;

        if current_role != 'querysead_owner' then
            raise exception 'This script must be run as querysead_worker!';
        end if;

        if current_database() not like 'sead_staging%' then
            raise exception 'This script must be run in sead_staging!';
        end if;


        set statement_timeout = 0;
        set lock_timeout = 0;
        set client_encoding = 'UTF8';
        set standard_conforming_strings = on;
        set check_function_bodies = false;
        set client_min_messages = warning;

        set search_path = facet, pg_catalog;

       insert into facet_group (facet_group_id, facet_group_key, display_title, is_applicable, is_default) (values
            (99, 'ROOT', 'ROOT', false, false),
            (1, 'others', 'Others', true, false),
            (2, 'space_time', 'Space/Time', true, false),
            (3, 'time', 'Time', true, false),
            (4, 'ecology', 'Ecology', true, false),
            (5, 'measured_values', 'Measured values', true, false),
            (6, 'taxonomy', 'Taxonomy', true, false)
        ) on conflict (facet_group_id) do update
            set facet_group_key = excluded.facet_group_key,
                display_title = excluded.display_title,
                is_applicable = excluded.is_applicable,
                is_default = excluded.is_default;

       insert into facet_type (facet_type_id, facet_type_name, reload_as_target) (values
            (9, 'undefined', false),
            (1, 'discrete', false),
            (2, 'range', true),
            (3, 'geo', true)
        ) on conflict (facet_type_id) do update
            set facet_type_name = excluded.facet_type_name,
                reload_as_target = excluded.reload_as_target;

       insert into facet (facet_id, facet_code, display_title, facet_group_id, facet_type_id, category_id_expr, category_name_expr, icon_id_expr, sort_expr, is_applicable, is_default, aggregate_type, aggregate_title, aggregate_facet_id) (values
            (1, 'result_facet', 'Analysis entities', 999, 1, 'tbl_analysis_entities.analysis_entity_id', 'tbl_physical_samples.sample_name||'' ''||tbl_datasets.dataset_name', 'tbl_analysis_entities.analysis_entity_id', 'tbl_datasets.dataset_name', false, false, 'count', 'Number of samples', 0),
            (2, 'dataset_helper', 'dataset_helper', 999, 1, 'tbl_datasets.dataset_id', 'tbl_datasets.dataset_id', 'tbl_dataset.dataset_id', 'tbl_dataset.dataset_id', false, false, 'count', 'Number of samples', 1),
            (25, 'species', 'Taxa', 6, 1, 'tbl_taxa_tree_master.taxon_id', 'concat_ws('' '', tbl_taxa_tree_genera.genus_name, tbl_taxa_tree_master.species, tbl_taxa_tree_authors.author_name)', 'tbl_taxa_tree_master.taxon_id', 'tbl_taxa_tree_genera.genus_name||'' ''||tbl_taxa_tree_master.species', true, false, 'sum', 'sum of Abundance', 32),
            (35, 'tbl_biblio_modern', 'Bibligraphy modern', 1, 1, 'metainformation.view_taxa_biblio.biblio_id', 'tbl_biblio.title||''  ''||tbl_biblio.author ', 'tbl_biblio.biblio_id', 'tbl_biblio.author', true, false, 'count', 'count of species', 19),
            (3, 'tbl_denormalized_measured_values_33_0', 'MS ', 5, 2, 'metainformation.tbl_denormalized_measured_values.value_33_0', 'metainformation.tbl_denormalized_measured_values.value_33_0', 'metainformation.tbl_denormalized_measured_values.value_33_0', 'metainformation.tbl_denormalized_measured_values.value_33_0', true, false, '', 'Number of samples', 1),
            (4, 'tbl_denormalized_measured_values_33_82', 'MS Heating 550', 5, 2, 'metainformation.tbl_denormalized_measured_values.value_33_82', 'metainformation.tbl_denormalized_measured_values.value_33_82', 'metainformation.tbl_denormalized_measured_values.value_33_82', 'metainformation.tbl_denormalized_measured_values.value_33_82', true, false, '', 'Number of samples', 1),
            (5, 'tbl_denormalized_measured_values_32', 'LOI', 5, 2, 'metainformation.tbl_denormalized_measured_values.value_32_0', 'metainformation.tbl_denormalized_measured_values.value_32_0', 'metainformation.tbl_denormalized_measured_values.value_32', 'metainformation.tbl_denormalized_measured_values.value_32', true, false, '', 'Number of samples', 1),
            (6, 'tbl_denormalized_measured_values_37', ' P┬░', 5, 2, 'metainformation.tbl_denormalized_measured_values.value_37_0', 'metainformation.tbl_denormalized_measured_values.value_37_0', 'metainformation.tbl_denormalized_measured_values.value_37', 'metainformation.tbl_denormalized_measured_values.value_37', true, false, '', 'Number of samples', 1),
            (7, 'measured_values_helper', 'values', 999, 1, 'tbl_measured_values.measured_value', 'tbl_measured_values.measured_value', 'tbl_measured_values.measured_value', 'tbl_measured_values.measured_value', false, false, 'count', 'Number of samples', 1),
            (8, 'taxon_result', 'taxon_id', 999, 1, 'tbl_abundances.taxon_id', 'tbl_abundances.taxon_id', 'tbl_abundances.taxon_id', 'tbl_abundances.taxon_id', false, false, 'count', 'Number of samples', 1),
            (9, 'map_result', 'Site', 999, 1, 'tbl_sites.site_id', 'tbl_sites.site_name', 'tbl_sites.site_id', 'tbl_sites.site_name', false, false, 'count', 'Number of samples', 1),
            (12, 'record_types', 'Proxy types', 1, 1, 'tbl_record_types.record_type_id', 'tbl_record_types.record_type_name', 'tbl_record_types.record_type_id', 'tbl_record_types.record_type_name', true, false, 'count', 'Number of samples', 1),
            (13, 'sample_groups', 'Sample group', 2, 1, 'tbl_sample_groups.sample_group_id', 'tbl_sample_groups.sample_group_name', 'tbl_sample_groups.sample_group_id', 'tbl_sample_groups.sample_group_name', true, true, 'count', 'Number of samples', 1),
            (14, 'places', 'Places', 2, 1, 'tbl_locations.location_id', 'tbl_locations.location_name', 'tbl_locations.location_id', 'tbl_locations.location_name', false, true, 'count', 'Number of samples', 1),
            (15, 'places_all2', 'view_places_relations', 2, 1, 'tbl_locations.location_id', 'tbl_locations.location_name', 'view_places_relations.rel_id', 'tbl_locations.location_name', false, true, 'count', 'Number of samples', 1),
            (16, 'sample_groups_helper', 'Sample group', 2, 1, 'tbl_sample_groups.sample_group_id', 'tbl_sample_groups.sample_group_name', 'tbl_sample_groups.sample_group_id', 'tbl_sample_groups.sample_group_name', false, true, 'count', 'Number of samples', 1),
            (17, 'physical_samples', 'physical samples', 2, 1, 'tbl_physical_samples.physical_sample_id', 'tbl_physical_samples.sample_name', 'tbl_physical_samples.physical_sample_id', 'tbl_physical_samples.sample_name', false, true, 'count', 'Number of samples', 1),
            (18, 'sites', 'Site', 2, 1, 'tbl_sites.site_id', 'tbl_sites.site_name', 'tbl_sites.site_id', 'tbl_sites.site_name', true, true, 'count', 'Number of samples', 1),
            (19, 'sites_helper', 'Site', 2, 1, 'tbl_sites.site_id', 'tbl_sites.site_name', 'tbl_sites.site_id', 'tbl_sites.site_name', false, true, 'count', 'Number of samples', 1),
            (21, 'country', 'Country', 2, 1, 'countries.location_id', 'countries.location_name ', 'countries.location_id', 'countries.location_name', true, false, 'count', 'Number of samples', 1),
            (22, 'ecocode', 'Eco code', 4, 1, 'tbl_ecocode_definitions.ecocode_definition_id', 'tbl_ecocode_definitions.label', 'tbl_ecocode_definitions.ecocode_definition_id', 'tbl_ecocode_definitions.label', true, false, 'count', 'Number of samples', 1),
            (23, 'family', 'Family', 6, 1, 'tbl_taxa_tree_families.family_id', 'tbl_taxa_tree_families.family_name ', 'tbl_taxa_tree_families.family_id', 'tbl_taxa_tree_families.family_name ', true, false, 'count', 'Number of samples', 1),
            (24, 'genus', 'Genus', 6, 1, 'tbl_taxa_tree_genera.genus_id', 'tbl_taxa_tree_genera.genus_name', 'tbl_taxa_tree_genera.genus_id', 'tbl_taxa_tree_genera.genus_name', true, false, 'count', 'Number of samples', 1),
            (26, 'species_helper', 'Species', 6, 1, 'tbl_taxa_tree_master.taxon_id', 'tbl_taxa_tree_master.taxon_id', 'tbl_taxa_tree_master.taxon_id', 'tbl_taxa_tree_master.species', false, false, 'count', 'Number of samples', 1),
            (27, 'abundance_helper', 'abundance_id', 6, 1, 'tbl_abundances.abundance_id', 'tbl_abundances.abundance_id', 'tbl_abundances.abundance_id', 'tbl_abundances.abundance_id', false, false, 'count', 'Number of samples', 1),
            (28, 'species_author', 'Author', 6, 1, 'tbl_taxa_tree_authors.author_id ', 'tbl_taxa_tree_authors.author_name ', 'tbl_taxa_tree_authors.author_id ', 'tbl_taxa_tree_authors.author_name ', true, false, 'count', 'Number of samples', 1),
            (29, 'feature_type', 'Feature type', 1, 1, 'tbl_feature_types.feature_type_id ', 'tbl_feature_types.feature_type_name', 'tbl_feature_types.feature_id ', 'tbl_feature_types.feature_type_name', true, false, 'count', 'Number of samples', 1),
            (30, 'ecocode_system', 'Eco code system', 4, 1, 'tbl_ecocode_systems.ecocode_system_id ', 'tbl_ecocode_systems.name', 'tbl_ecocode_systems.ecocode_system_id ', 'tbl_ecocode_systems.definition', true, false, 'count', 'Number of samples', 1),
            (31, 'abundance_classification', 'abundance classification', 4, 1, 'metainformation.view_abundance.elements_part_mod ', 'metainformation.view_abundance.elements_part_mod ', 'metainformation.view_abundance.elements_part_mod ', 'metainformation.view_abundance.elements_part_mod ', true, false, 'count', 'Number of samples', 1),
            (10, 'geochronology', 'Geochronology', 2, 2, 'tbl_geochronology.age', 'tbl_geochronology.age', 'tbl_geochronology.age', 'tbl_geochronology.age', true, false, '', 'Number of samples', 1),
            (11, 'relative_age_name', 'Time periods', 2, 1, 'tbl_relative_ages.relative_age_id', 'tbl_relative_ages.relative_age_name', 'tbl_relative_ages.relative_age_id', 'tbl_relative_ages.relative_age_name', true, false, 'count', 'Number of samples', 1),
            (20, 'tbl_relative_dates_helper', 'tbl_relative_dates', 2, 1, 'tbl_relative_dates.relative_age_id', 'tbl_relative_dates.relative_age_name ', 'tbl_relative_dates.relative_age_name', 'tbl_relative_dates.relative_age_name ', false, false, 'count', 'Number of samples', 1),
            (34, 'activeseason', 'Seasons', 2, 1, 'tbl_seasons.season_id', 'tbl_seasons.season_name ', 'tbl_seasons.season_id', 'tbl_seasons.season_type ', true, false, 'count', 'Number of samples', 1),
            (32, 'abundances_all_helper', 'Abundances', 4, 2, 'metainformation.view_abundance.abundance ', 'metainformation.view_abundance.abundance ', 'metainformation.view_abundance.abundance ', 'metainformation.view_abundance.abundance', false, false, '', 'Number of samples', 1),
            (33, 'abundances_all', 'Abundances', 4, 2, 'metainformation.view_abundance.abundance ', 'metainformation.view_abundance.abundance ', 'metainformation.view_abundance.abundance ', 'metainformation.view_abundance.abundance', true, false, '', 'Number of samples', 1),
            (36, 'tbl_biblio_sample_groups', 'Bibligraphy sites/Samplegroups', 1, 1, 'tbl_biblio.biblio_id', 'tbl_biblio.title||''  ''||tbl_biblio.author', 'tbl_biblio.biblio_id', 'tbl_biblio.author', true, false, 'count', 'Number of samples', 1),
            (37, 'tbl_biblio_sites', 'Bibligraphy sites', 1, 1, 'tbl_biblio.biblio_id', 'tbl_biblio.title||''  ''||tbl_biblio.author', 'tbl_biblio.biblio_id', 'tbl_biblio.author', false, false, 'count', 'Number of samples', 1)
        ) on conflict (facet_id) to update
            set facet_code = excluded.facet_code,
                display_title = excluded.display_title,
                facet_group_id = excluded.facet_group_id,
                facet_type_id = excluded.facet_type_id,
                category_id_expr = excluded.category_id_expr,
                category_name_expr = excluded.category_name_expr,
                icon_id_expr = excluded.icon_id_expr,
                sort_expr = excluded.sort_expr,
                is_applicable = excluded.is_applicable,
                is_default = excluded.is_default,
                aggregate_type = excluded.aggregate_type,
                aggregate_title = excluded.aggregate_title,
                aggregate_facet_id = excluded.aggregate_facet_id;

        insert into facet.facet_condition_clause (facet_source_table_id, facet_id, clause) (values
            (1, 21, 'countries.location_type_id=1'),
            (2, 25, 'tbl_sites.site_id is not null'),
            (3, 32, 'metainformation.view_abundance.abundance is not null'),
            (4, 33, 'metainformation.view_abundance.abundance is not null'),
            (5, 36, 'metainformation.view_sample_group_references.biblio_id is not null'),
            (6, 37, 'metainformation.view_site_references.biblio_id is not null')
        ) on conflict (facet_source_table_id) do update
            set facet_id = excluded.facet_id,
                clause = excluded.clause;

       insert into facet.facet_table (facet_table_id, facet_id, sequence_id, schema_name, table_name, alias) (values
            (1, 1, 1, '', 'tbl_analysis_entities', ''),
            (2, 2, 1, '', 'tbl_datasets', ''),
            (3, 3, 1, '', 'metainformation.tbl_denormalized_measured_values', ''),
            (4, 4, 1, '', 'metainformation.tbl_denormalized_measured_values', ''),
            (5, 5, 1, '', 'metainformation.tbl_denormalized_measured_values', ''),
            (6, 6, 1, '', 'metainformation.tbl_denormalized_measured_values', ''),
            (7, 7, 1, '', 'tbl_measured_values', ''),
            (8, 8, 1, '', 'tbl_abundances', ''),
            (9, 9, 1, '', 'tbl_sites', ''),
            (10, 10, 1, '', 'tbl_geochronology', ''),
            (11, 11, 1, '', 'tbl_relative_ages', ''),
            (12, 12, 1, '', 'tbl_record_types', ''),
            (13, 13, 1, '', 'tbl_sample_groups', ''),
            (14, 14, 1, '', 'tbl_locations', ''),
            (15, 15, 1, '', 'view_places_relations', ''),
            (16, 16, 1, '', 'tbl_sample_groups', ''),
            (17, 17, 1, '', 'tbl_physical_samples', ''),
            (18, 18, 1, '', 'tbl_sites', ''),
            (19, 19, 1, '', 'tbl_sites', ''),
            (20, 20, 1, '', 'tbl_relative_dates', ''),
            (21, 21, 1, '', 'tbl_locations', 'countries'),
            (22, 22, 1, '', 'tbl_ecocode_definitions', ''),
            (23, 23, 1, '', 'tbl_taxa_tree_families', ''),
            (24, 24, 1, '', 'tbl_taxa_tree_genera', ''),
            (25, 25, 1, '', 'tbl_taxa_tree_master', ''),
            (26, 26, 1, '', 'tbl_taxa_tree_master', ''),
            (27, 27, 1, '', 'tbl_abundances', ''),
            (28, 28, 1, '', 'tbl_taxa_tree_authors', ''),
            (29, 29, 1, '', 'tbl_feature_types', ''),
            (30, 30, 1, '', 'tbl_ecocode_systems', ''),
            (31, 31, 1, '', 'metainformation.view_abundance', ''),
            (32, 32, 1, '', 'metainformation.view_abundance', ''),
            (33, 33, 1, '', 'metainformation.view_abundance', ''),
            (34, 34, 1, '', 'tbl_seasons', ''),
            (35, 35, 1, '', 'metainformation.view_taxa_biblio', ''),
            (36, 36, 1, '', 'tbl_biblio', ''),
            (37, 37, 1, '', 'tbl_biblio', ''),
            (38, 1, 2, '', 'tbl_physical_samples', ''),
            (39, 14, 2, '', 'tbl_site_locations', ''),
            (40, 15, 2, '', 'tbl_locations', ''),
            (41, 21, 2, '', 'tbl_site_locations', ''),
            (42, 22, 2, '', 'tbl_ecocode_definitions', ''),
            (43, 23, 2, '', 'tbl_taxa_tree_families', ''),
            (44, 24, 2, '', 'tbl_taxa_tree_genera', ''),
            (45, 25, 2, '', 'tbl_taxa_tree_genera', ''),
            (46, 26, 2, '', 'tbl_taxa_tree_genera', ''),
            (47, 28, 2, '', 'tbl_taxa_tree_authors', ''),
            (48, 29, 2, '', 'tbl_physical_sample_features', ''),
            (49, 30, 2, '', 'tbl_ecocode_systems', ''),
            (50, 35, 2, '', 'tbl_biblio', ''),
            (51, 36, 2, '', 'metainformation.view_sample_group_references', ''),
            (52, 37, 2, '', 'metainformation.view_site_references', ''),
            (57, 25, 4, '', 'tbl_sites', ''),
            (53, 1, 3, '', 'tbl_datasets', ''),
            (54, 15, 3, '', 'tbl_site_locations', ''),
            (55, 25, 3, '', 'tbl_taxa_tree_authors', ''),
            (56, 26, 3, '', 'tbl_taxa_tree_authors', '')
        ) on conflict (facet_table_id) do update
            set facet_id = excluded.facet_id,
                sequence_id = excluded.sequence_id,
                schema_name = excluded.schema_name,
                table_name = excluded.table_name,
                alias = excluded.alias;

       insert into facet.graph_table (table_id, table_name) (values
            (1, 'tbl_horizons'),
            (2, 'tbl_aggregate_samples'),
            (3, 'tbl_analysis_entity_prep_methods'),
            (4, 'tbl_analysis_entities'),
            (5, 'tbl_dating_uncertainty'),
            (6, 'tbl_feature_types'),
            (7, 'view_places_relations'),
            (8, 'tbl_sample_coordinates'),
            (9, 'tbl_project_stages'),
            (10, 'tbl_sample_alt_refs'),
            (11, 'tbl_activity_types'),
            (12, 'tbl_measured_value_dimensions'),
            (13, 'tbl_taxa_synonyms'),
            (14, 'tbl_colours'),
            (15, 'tbl_site_references'),
            (16, 'tbl_image_types'),
            (17, 'tbl_project_types'),
            (18, 'tbl_mcr_names'),
            (19, 'tbl_mcr_summary_data'),
            (20, 'tbl_taxa_images'),
            (21, 'tbl_taxonomic_order'),
            (22, 'tbl_imported_taxa_replacements'),
            (23, 'tbl_dendro_measurement_lookup'),
            (24, 'tbl_rdb_codes'),
            (25, 'metainformation.view_abundances_by_taxon_analysis_entity'),
            (26, 'metainformation.view_site_references'),
            (27, 'tbl_taxa_seasonality'),
            (28, 'tbl_sample_group_description_type_sampling_contexts'),
            (29, 'tbl_contacts'),
            (30, 'tbl_sample_group_coordinates'),
            (31, 'tbl_tephras'),
            (32, 'tbl_sample_colours'),
            (33, 'tbl_method_groups'),
            (34, 'tbl_keywords'),
            (35, 'tbl_locations'),
            (36, 'tbl_taxa_tree_families'),
            (37, 'tbl_relative_age_types'),
            (38, 'tbl_abundance_elements'),
            (39, 'tbl_taxa_tree_authors'),
            (40, 'tbl_sample_group_sampling_contexts'),
            (41, 'tbl_sample_horizons'),
            (42, 'tbl_sample_group_references'),
            (43, 'tbl_taxonomic_order_systems'),
            (44, 'tbl_abundance_modifications'),
            (45, 'tbl_taxa_tree_orders'),
            (46, 'countries'),
            (47, 'tbl_aggregate_order_types'),
            (48, 'tbl_rdb'),
            (49, 'tbl_sample_locations'),
            (50, 'tbl_abundance_ident_levels'),
            (51, 'tbl_ecocode_groups'),
            (52, 'tbl_sample_group_notes'),
            (53, 'tbl_taxonomy_notes'),
            (54, 'tbl_sample_group_description_types'),
            (55, 'tbl_relative_dates'),
            (56, 'tbl_sample_description_sample_group_contexts'),
            (57, 'metainformation.view_abundance'),
            (58, 'tbl_projects'),
            (59, 'tbl_chron_controls'),
            (60, 'tbl_geochronology'),
            (61, 'tbl_sample_images'),
            (62, 'tbl_ecocode_definitions'),
            (63, 'tbl_taxonomic_order_biblio'),
            (64, 'tbl_site_images'),
            (65, 'tbl_sample_location_type_sampling_contexts'),
            (66, 'tbl_publishers'),
            (67, 'tbl_text_identification_keys'),
            (68, 'tbl_relative_age_refs'),
            (69, 'tbl_dendro'),
            (70, 'tbl_mcrdata_birmbeetledat'),
            (71, 'tbl_relative_ages'),
            (72, 'tbl_units'),
            (73, 'tbl_sample_description_types'),
            (74, 'tbl_years_types'),
            (75, 'tbl_features'),
            (76, 'tbl_dataset_masters'),
            (77, 'tbl_site_other_records'),
            (78, 'tbl_site_natgridrefs'),
            (79, 'tbl_languages'),
            (80, 'tbl_lithology'),
            (81, 'tbl_ceramics_measurement_lookup'),
            (82, 'tbl_seasons'),
            (83, 'tbl_dataset_contacts'),
            (84, 'tbl_biblio'),
            (85, 'tbl_dating_labs'),
            (86, 'tbl_datasets'),
            (87, 'tbl_geochron_refs'),
            (88, 'tbl_abundances'),
            (89, 'tbl_methods'),
            (90, 'tbl_text_distribution'),
            (91, 'tbl_sample_groups'),
            (92, 'tbl_location_types'),
            (93, 'tbl_analysis_entity_dimensions'),
            (94, 'tbl_sample_notes'),
            (95, 'tbl_site_preservation_status'),
            (96, 'tbl_analysis_entity_ages'),
            (97, 'tbl_ceramics_measurements'),
            (98, 'tbl_dimensions'),
            (99, 'metainformation.view_taxa_biblio'),
            (100, 'tbl_dendro_measurements'),
            (101, 'tbl_ecocodes'),
            (102, 'tbl_physical_samples'),
            (103, 'tbl_taxa_common_names'),
            (104, 'tbl_data_type_groups'),
            (105, 'tbl_sample_types'),
            (106, 'tbl_coordinate_method_dimensions'),
            (107, 'tbl_tephra_dates'),
            (108, 'tbl_season_types'),
            (109, 'tbl_taxa_tree_master'),
            (110, 'tbl_record_types'),
            (111, 'tbl_sample_descriptions'),
            (112, 'tbl_sample_group_dimensions'),
            (113, 'tbl_site_locations'),
            (114, 'metainformation.view_sample_group_references'),
            (115, 'tbl_aggregate_sample_ages'),
            (116, 'tbl_sample_dimensions'),
            (117, 'tbl_chronologies'),
            (118, 'tbl_species_association_types'),
            (119, 'tbl_sites'),
            (120, 'tbl_collections_or_journals'),
            (121, 'tbl_measured_values'),
            (122, 'tbl_text_biology'),
            (123, 'tbl_contact_types'),
            (124, 'tbl_sample_group_images'),
            (125, 'metainformation.tbl_denormalized_measured_values'),
            (126, 'tbl_taxa_measured_attributes'),
            (127, 'tbl_dendro_date_notes'),
            (128, 'tbl_ecocode_systems'),
            (129, 'tbl_tephra_refs'),
            (130, 'tbl_sample_group_descriptions'),
            (131, 'tbl_species_associations'),
            (132, 'tbl_physical_sample_features'),
            (133, 'tbl_dataset_submissions'),
            (134, 'tbl_dating_material'),
            (135, 'tbl_data_types'),
            (136, 'tbl_alt_ref_types'),
            (137, 'tbl_biblio_keywords'),
            (138, 'tbl_dendro_dates'),
            (139, 'tbl_ceramics'),
            (140, 'tbl_dataset_submission_types'),
            (141, 'tbl_taxa_reference_specimens'),
            (142, 'tbl_modification_types'),
            (143, 'tbl_rdb_systems'),
            (144, 'tbl_sample_location_types'),
            (145, 'tbl_aggregate_datasets'),
            (146, 'tbl_identification_levels'),
            (147, 'tbl_chron_control_types'),
            (148, 'tbl_taxa_tree_genera')
        ) on conflict (table_id) do update
            set table_name = excluded.table_name;

       insert into facet.graph_table_relation (relation_id, source_table_id, target_table_id, weight, source_column_name, target_column_name) (values
            (1, 38, 110, 20, 'record_type_id', 'record_type_id'),
        	(2, 50, 88, 20, 'abundance_id', 'abundance_id'),
        	(3, 50, 146, 20, 'identification_level_id', 'identification_level_id'),
        	(4, 44, 88, 20, 'abundance_id', 'abundance_id'),
        	(5, 44, 142, 20, 'modification_type_id', 'modification_type_id'),
        	(6, 88, 38, 20, 'abundance_element_id', 'abundance_element_id'),
        	(7, 88, 109, 20, 'taxon_id', 'taxon_id'),
        	(8, 145, 47, 20, 'aggregate_order_type_id', 'aggregate_order_type_id'),
        	(9, 115, 145, 20, 'aggregate_dataset_id', 'aggregate_dataset_id'),
        	(10, 115, 96, 20, 'analysis_entity_age_id', 'analysis_entity_age_id'),
        	(11, 2, 145, 20, 'aggregate_dataset_id', 'aggregate_dataset_id'),
        	(12, 2, 4, 20, 'analysis_entity_id', 'analysis_entity_id'),
        	(13, 96, 4, 20, 'analysis_entity_id', 'analysis_entity_id'),
        	(14, 96, 117, 20, 'chronology_id', 'chronology_id'),
        	(15, 93, 4, 20, 'analysis_entity_id', 'analysis_entity_id'),
        	(16, 93, 98, 20, 'dimension_id', 'dimension_id'),
        	(17, 3, 4, 20, 'analysis_entity_id', 'analysis_entity_id'),
        	(18, 3, 89, 20, 'method_id', 'method_id'),
        	(19, 137, 84, 20, 'biblio_id', 'biblio_id'),
        	(20, 137, 34, 20, 'keyword_id', 'keyword_id'),
        	(21, 139, 4, 20, 'analysis_entity_id', 'analysis_entity_id'),
        	(22, 139, 97, 20, 'ceramics_measurement_id', 'ceramics_measurement_id'),
        	(23, 81, 97, 20, 'ceramics_measurement_id', 'ceramics_measurement_id'),
        	(24, 97, 89, 20, 'method_id', 'method_id'),
        	(25, 59, 147, 20, 'chron_control_type_id', 'chron_control_type_id'),
        	(26, 59, 117, 20, 'chronology_id', 'chronology_id'),
        	(27, 117, 29, 20, 'contact_id', 'contact_id'),
        	(28, 117, 91, 20, 'sample_group_id', 'sample_group_id'),
        	(29, 120, 66, 20, 'publisher_id', 'publisher_id'),
        	(30, 14, 89, 20, 'method_id', 'method_id'),
        	(31, 106, 98, 20, 'dimension_id', 'dimension_id'),
        	(32, 106, 89, 20, 'method_id', 'method_id'),
        	(33, 83, 29, 20, 'contact_id', 'contact_id'),
        	(34, 83, 123, 20, 'contact_type_id', 'contact_type_id'),
        	(35, 83, 86, 20, 'dataset_id', 'dataset_id'),
        	(36, 76, 29, 20, 'contact_id', 'contact_id'),
        	(37, 86, 135, 20, 'data_type_id', 'data_type_id'),
        	(38, 86, 76, 20, 'master_set_id', 'master_set_id'),
        	(39, 86, 58, 20, 'project_id', 'project_id'),
        	(40, 86, 86, 20, 'updated_dataset_id', 'dataset_id'),
        	(41, 133, 29, 20, 'contact_id', 'contact_id'),
        	(42, 133, 86, 20, 'dataset_id', 'dataset_id'),
        	(43, 133, 140, 20, 'submission_type_id', 'submission_type_id'),
        	(44, 135, 104, 20, 'data_type_group_id', 'data_type_group_id'),
        	(45, 85, 29, 20, 'contact_id', 'contact_id'),
        	(46, 134, 38, 20, 'abundance_element_id', 'abundance_element_id'),
        	(47, 134, 60, 20, 'geochron_id', 'geochron_id'),
        	(48, 134, 109, 20, 'taxon_id', 'taxon_id'),
        	(49, 69, 4, 20, 'analysis_entity_id', 'analysis_entity_id'),
        	(50, 69, 100, 20, 'dendro_measurement_id', 'dendro_measurement_id'),
        	(51, 127, 138, 20, 'dendro_date_id', 'dendro_date_id'),
        	(52, 138, 4, 20, 'analysis_entity_id', 'analysis_entity_id'),
        	(53, 138, 5, 20, 'dating_uncertainty_id', 'dating_uncertainty_id'),
        	(54, 138, 74, 20, 'years_type_id', 'years_type_id'),
        	(55, 23, 100, 20, 'dendro_measurement_id', 'dendro_measurement_id'),
        	(56, 100, 89, 20, 'method_id', 'method_id'),
        	(57, 98, 33, 20, 'method_group_id', 'method_group_id'),
        	(58, 98, 72, 20, 'unit_id', 'unit_id'),
        	(59, 62, 51, 20, 'ecocode_group_id', 'ecocode_group_id'),
        	(60, 51, 128, 20, 'ecocode_system_id', 'ecocode_system_id'),
        	(61, 101, 62, 20, 'ecocode_definition_id', 'ecocode_definition_id'),
        	(62, 101, 109, 20, 'taxon_id', 'taxon_id'),
        	(63, 75, 6, 20, 'feature_type_id', 'feature_type_id'),
        	(64, 60, 4, 20, 'analysis_entity_id', 'analysis_entity_id'),
        	(65, 60, 85, 20, 'dating_lab_id', 'dating_lab_id'),
        	(66, 60, 5, 20, 'dating_uncertainty_id', 'dating_uncertainty_id'),
        	(67, 87, 60, 20, 'geochron_id', 'geochron_id'),
        	(68, 22, 109, 20, 'taxon_id', 'taxon_id'),
        	(69, 80, 91, 20, 'sample_group_id', 'sample_group_id'),
        	(70, 145, 84, 150, 'biblio_id', 'biblio_id'),
        	(71, 4, 86, 1, 'dataset_id', 'dataset_id'),
        	(72, 4, 102, 1, 'physical_sample_id', 'physical_sample_id'),
        	(73, 86, 89, 1, 'method_id', 'method_id'),
        	(74, 86, 84, 150, 'biblio_id', 'biblio_id'),
        	(75, 128, 84, 150, 'biblio_id', 'biblio_id'),
        	(76, 87, 84, 150, 'biblio_id', 'biblio_id'),
        	(77, 1, 89, 70, 'method_id', 'method_id'),
        	(78, 76, 84, 200, 'biblio_id', 'biblio_id'),
        	(79, 35, 92, 20, 'location_type_id', 'location_type_id'),
        	(80, 70, 109, 20, 'taxon_id', 'taxon_id'),
        	(81, 18, 109, 20, 'taxon_id', 'taxon_id'),
        	(82, 19, 109, 20, 'taxon_id', 'taxon_id'),
        	(83, 12, 98, 20, 'dimension_id', 'dimension_id'),
        	(84, 12, 121, 20, 'measured_value_id', 'measured_value_id'),
        	(85, 121, 4, 20, 'analysis_entity_id', 'analysis_entity_id'),
        	(86, 89, 33, 20, 'method_group_id', 'method_group_id'),
        	(87, 89, 110, 20, 'record_type_id', 'record_type_id'),
        	(88, 132, 75, 20, 'feature_id', 'feature_id'),
        	(89, 132, 102, 20, 'physical_sample_id', 'physical_sample_id'),
        	(90, 102, 136, 20, 'alt_ref_type_id', 'alt_ref_type_id'),
        	(91, 102, 105, 20, 'sample_type_id', 'sample_type_id'),
        	(92, 58, 9, 20, 'project_stage_id', 'project_stage_id'),
        	(93, 58, 17, 20, 'project_type_id', 'project_type_id'),
        	(94, 48, 24, 20, 'rdb_code_id', 'rdb_code_id'),
        	(95, 48, 109, 20, 'taxon_id', 'taxon_id'),
        	(96, 24, 143, 20, 'rdb_system_id', 'rdb_system_id'),
        	(97, 68, 71, 20, 'relative_age_id', 'relative_age_id'),
        	(98, 71, 37, 20, 'relative_age_type_id', 'relative_age_type_id'),
        	(99, 55, 5, 20, 'dating_uncertainty_id', 'dating_uncertainty_id'),
        	(100, 55, 102, 20, 'physical_sample_id', 'physical_sample_id'),
        	(101, 55, 71, 20, 'relative_age_id', 'relative_age_id'),
        	(102, 10, 136, 20, 'alt_ref_type_id', 'alt_ref_type_id'),
        	(103, 10, 102, 20, 'physical_sample_id', 'physical_sample_id'),
        	(104, 32, 14, 20, 'colour_id', 'colour_id'),
        	(105, 32, 102, 20, 'physical_sample_id', 'physical_sample_id'),
        	(106, 8, 106, 20, 'coordinate_method_dimension_id', 'coordinate_method_dimension_id'),
        	(107, 8, 102, 20, 'physical_sample_id', 'physical_sample_id'),
        	(108, 111, 102, 20, 'physical_sample_id', 'physical_sample_id'),
        	(109, 111, 73, 20, 'sample_description_type_id', 'sample_description_type_id'),
        	(110, 56, 73, 20, 'sample_description_type_id', 'sample_description_type_id'),
        	(111, 56, 40, 20, 'sampling_context_id', 'sampling_context_id'),
        	(112, 116, 98, 20, 'dimension_id', 'dimension_id'),
        	(113, 116, 102, 20, 'physical_sample_id', 'physical_sample_id'),
        	(114, 30, 106, 20, 'coordinate_method_dimension_id', 'coordinate_method_dimension_id'),
        	(115, 30, 91, 20, 'sample_group_id', 'sample_group_id'),
        	(116, 130, 54, 20, 'sample_group_description_type_id', 'sample_group_description_type_id'),
        	(117, 130, 91, 20, 'sample_group_id', 'sample_group_id'),
        	(118, 28, 54, 20, 'sample_group_description_type_id', 'sample_group_description_type_id'),
        	(119, 28, 40, 20, 'sampling_context_id', 'sampling_context_id'),
        	(120, 112, 98, 20, 'dimension_id', 'dimension_id'),
        	(121, 112, 91, 20, 'sample_group_id', 'sample_group_id'),
        	(122, 124, 16, 20, 'image_type_id', 'image_type_id'),
        	(123, 124, 91, 20, 'sample_group_id', 'sample_group_id'),
        	(124, 52, 91, 20, 'sample_group_id', 'sample_group_id'),
        	(125, 42, 91, 20, 'sample_group_id', 'sample_group_id'),
        	(126, 91, 40, 20, 'sampling_context_id', 'sampling_context_id'),
        	(127, 41, 1, 20, 'horizon_id', 'horizon_id'),
        	(128, 41, 102, 20, 'physical_sample_id', 'physical_sample_id'),
        	(129, 61, 16, 20, 'image_type_id', 'image_type_id'),
        	(130, 61, 102, 20, 'physical_sample_id', 'physical_sample_id'),
        	(131, 49, 102, 20, 'physical_sample_id', 'physical_sample_id'),
        	(132, 49, 144, 20, 'sample_location_type_id', 'sample_location_type_id'),
        	(133, 65, 144, 20, 'sample_location_type_id', 'sample_location_type_id'),
        	(134, 65, 40, 20, 'sampling_context_id', 'sampling_context_id'),
        	(135, 94, 102, 20, 'physical_sample_id', 'physical_sample_id'),
        	(136, 82, 108, 20, 'season_type_id', 'season_type_id'),
        	(137, 64, 29, 20, 'contact_id', 'contact_id'),
        	(138, 64, 16, 20, 'image_type_id', 'image_type_id'),
        	(139, 64, 119, 20, 'site_id', 'site_id'),
        	(140, 113, 119, 20, 'site_id', 'site_id'),
        	(141, 89, 84, 150, 'biblio_id', 'biblio_id'),
        	(142, 102, 91, 1, 'sample_group_id', 'sample_group_id'),
        	(143, 48, 35, 150, 'location_id', 'location_id'),
        	(144, 143, 84, 150, 'biblio_id', 'biblio_id'),
        	(145, 143, 35, 150, 'location_id', 'location_id'),
        	(146, 68, 84, 150, 'biblio_id', 'biblio_id'),
        	(147, 55, 89, 70, 'method_id', 'method_id'),
        	(148, 116, 89, 150, 'method_id', 'method_id'),
        	(149, 91, 89, 150, 'method_id', 'method_id'),
        	(150, 91, 119, 1, 'site_id', 'site_id'),
        	(151, 113, 35, 5, 'location_id', 'location_id'),
        	(152, 42, 84, 90, 'biblio_id', 'biblio_id'),
        	(153, 78, 89, 20, 'method_id', 'method_id'),
        	(154, 78, 119, 20, 'site_id', 'site_id'),
        	(155, 95, 119, 20, 'site_id', 'site_id'),
        	(156, 15, 119, 20, 'site_id', 'site_id'),
        	(157, 131, 118, 20, 'association_type_id', 'association_type_id'),
        	(158, 131, 109, 20, 'taxon_id', 'taxon_id'),
        	(159, 103, 79, 20, 'language_id', 'language_id'),
        	(160, 103, 109, 20, 'taxon_id', 'taxon_id'),
        	(161, 20, 16, 20, 'image_type_id', 'image_type_id'),
        	(162, 20, 109, 20, 'taxon_id', 'taxon_id'),
        	(163, 126, 109, 20, 'taxon_id', 'taxon_id'),
        	(164, 141, 29, 20, 'contact_id', 'contact_id'),
        	(165, 141, 109, 20, 'taxon_id', 'taxon_id'),
        	(166, 27, 11, 20, 'activity_type_id', 'activity_type_id'),
        	(167, 27, 82, 20, 'season_id', 'season_id'),
        	(168, 27, 109, 20, 'taxon_id', 'taxon_id'),
        	(169, 109, 39, 20, 'author_id', 'author_id'),
        	(170, 21, 109, 20, 'taxon_id', 'taxon_id'),
        	(171, 21, 43, 20, 'taxonomic_order_system_id', 'taxonomic_order_system_id'),
        	(172, 63, 43, 20, 'taxonomic_order_system_id', 'taxonomic_order_system_id'),
        	(173, 53, 109, 20, 'taxon_id', 'taxon_id'),
        	(174, 107, 4, 20, 'analysis_entity_id', 'analysis_entity_id'),
        	(175, 107, 5, 20, 'dating_uncertainty_id', 'dating_uncertainty_id'),
        	(176, 107, 31, 20, 'tephra_id', 'tephra_id'),
        	(177, 129, 31, 20, 'tephra_id', 'tephra_id'),
        	(178, 122, 109, 20, 'taxon_id', 'taxon_id'),
        	(179, 90, 109, 20, 'taxon_id', 'taxon_id'),
        	(180, 67, 109, 20, 'taxon_id', 'taxon_id'),
        	(181, 88, 4, 1, 'analysis_entity_id', 'analysis_entity_id'),
        	(182, 89, 72, 150, 'unit_id', 'unit_id'),
        	(183, 71, 35, 70, 'location_id', 'location_id'),
        	(184, 77, 84, 150, 'biblio_id', 'biblio_id'),
        	(185, 77, 119, 150, 'site_id', 'site_id'),
        	(186, 77, 110, 150, 'record_type_id', 'record_type_id'),
        	(187, 131, 84, 150, 'biblio_id', 'biblio_id'),
        	(188, 27, 35, 60, 'location_id', 'location_id'),
        	(189, 13, 39, 150, 'author_id', 'author_id'),
        	(190, 13, 84, 150, 'biblio_id', 'biblio_id'),
        	(191, 122, 84, 150, 'biblio_id', 'biblio_id'),
        	(192, 13, 36, 150, 'family_id', 'family_id'),
        	(193, 13, 148, 150, 'genus_id', 'genus_id'),
        	(194, 13, 109, 150, 'taxon_id', 'taxon_id'),
        	(195, 36, 45, 1, 'order_id', 'order_id'),
        	(196, 148, 36, 1, 'family_id', 'family_id'),
        	(197, 109, 148, 1, 'genus_id', 'genus_id'),
        	(198, 45, 110, 1, 'record_type_id', 'record_type_id'),
        	(199, 63, 84, 150, 'biblio_id', 'biblio_id'),
        	(200, 53, 84, 150, 'biblio_id', 'biblio_id'),
        	(201, 90, 84, 150, 'biblio_id', 'biblio_id'),
        	(202, 67, 84, 150, 'biblio_id', 'biblio_id'),
        	(203, 129, 84, 150, 'biblio_id', 'biblio_id'),
        	(204, 46, 7, 20, 'location_id', 'rel_to_id'),
        	(205, 35, 7, 1, 'location_id', 'rel_to_id'),
        	(206, 15, 84, 90, 'biblio_id', 'biblio_id'),
        	(207, 102, 125, 20, 'physical_sample_id', 'physical_sample_id'),
        	(208, 25, 109, 20, 'taxon_id', 'taxon_id'),
        	(209, 25, 4, 20, 'analysis_entity_id', 'analysis_entity_id'),
        	(211, 57, 109, 20, 'taxon_id', 'taxon_id'),
        	(212, 114, 84, 80, 'biblio_id', 'biblio_id'),
        	(213, 114, 91, 15, 'sample_group_id', 'sample_group_id'),
        	(214, 26, 84, 80, 'biblio_id', 'biblio_id'),
        	(215, 26, 119, 15, 'site_id', 'site_id'),
        	(216, 99, 84, 10, 'biblio_id', 'biblio_id'),
        	(217, 99, 109, 2, 'taxon_id', 'taxon_id'),
        	(210, 57, 4, 2, 'analysis_entity_id', 'analysis_entity_id')
        ) on conflict (relation_id) do update
            set source_table_id = excluded.source_table_id,
                target_table_id = excluded.target_table_id,
                weight = excluded.weight,
                source_column_name = excluded.source_column_name,
                target_column_name = excluded.target_column_name;

       insert into facet.result_aggregate (aggregate_id, aggregate_key, display_text, is_applicable, is_activated, input_type, has_selector) (values
            (1, 'site_level', 'Site level', false, true, 'checkboxes', true),
            (2, 'aggregate_all', 'Aggregate all', false, true, 'checkboxes', true),
            (3, 'sample_group_level', 'Sample group level', false, true, 'checkboxes', true),
            (4, 'map_result', 'Map result', false, false, 'checkboxes', false)
        ) on conflict (aggregate_id) do update
            set aggregate_key = excluded.aggregate_key,
                display_text = excluded.display_text,
                is_applicable = excluded.is_applicable,
                is_activated = excluded.is_activated,
                input_type = excluded.input_type,
                has_selector = excluded.has_selector;

       insert into facet.result_field_type (field_type_id, is_result_value, sql_field_compiler, is_aggregate_field, is_sort_field, is_item_field, sql_template) (values
            ('sum_item', true, 'TemplateFieldCompiler', true, false, false, 'SUM({0}::double precision) AS sum_of_{0}'),
            ('count_item', true, 'TemplateFieldCompiler', true, false, false, 'COUNT({0}) AS count_of_{0}'),
            ('avg_item', true, 'TemplateFieldCompiler', true, false, false, 'AVG({0}) AS avg_of_{0}'),
            ('text_agg_item', true, 'TemplateFieldCompiler', true, false, false, 'ARRAY_TO_STRING(ARRAY_AGG(DISTINCT {0}),'','') AS text_agg_of_{0}'),
            ('single_item', true, 'TemplateFieldCompiler', false, false, true, '{0}'),
            ('link_item', true, 'TemplateFieldCompiler', false, false, true, '{0}'),
            ('link_item_filtered', true, 'TemplateFieldCompiler', false, false, true, '{0}'),
            ('sort_item', false, 'TemplateFieldCompiler', false, true, false, '{0}')
        ) on conflict (field_type_id) do update
            set is_result_value = excluded.is_result_value,
                sql_field_compiler = excluded.sql_field_compiler,
                is_aggregate_field = excluded.is_aggregate_field,
                is_sort_field = excluded.is_sort_field,
                is_item_field = excluded.is_item_field,
                sql_template = excluded.sql_template;

       insert into facet.result_field (result_field_id, result_field_key, table_name, column_name, display_text, field_type_id, activated, link_url, link_label) (values
            (1, 'sitename', 'tbl_sites', 'tbl_sites.site_name', 'Site name', 'single_item', true, NULL, NULL),
            (2, 'record_type', 'tbl_record_types', 'tbl_record_types.record_type_name', 'Record type(s)', 'text_agg_item', true, NULL, NULL),
            (3, 'analysis_entities', 'tbl_analysis_entities', 'tbl_analysis_entities.analysis_entity_id', 'Filtered records', 'single_item', true, NULL, NULL),
            (4, 'site_link', 'tbl_sites', 'tbl_sites.site_id', 'Full report', 'link_item', true, 'api/report/show_site_details.php?site_id', 'Show site report'),
            (5, 'site_link_filtered', 'tbl_sites', 'tbl_sites.site_id', 'Filtered report', 'link_item', true, 'api/report/show_site_details.php?site_id', 'Show filtered report'),
            (6, 'aggregate_all_filtered', 'tbl_aggregate_samples', '''Aggregated''::text', 'Filtered report', 'link_item_filtered', true, 'api/report/show_details_all_levels.php?level', NULL),
            (7, 'sample_group_link', 'tbl_sample_groups', 'tbl_sample_groups.sample_group_id', 'Full report', 'link_item', true, 'api/report/show_sample_group_details.php?sample_group_id', NULL),
            (8, 'sample_group_link_filtered', 'tbl_sample_groups', 'tbl_sample_groups.sample_group_id', 'Filtered report', 'link_item', true, 'api/report/show_sample_group_details.php?sample_group_id', NULL),
            (9, 'abundance', 'tbl_abundances', 'tbl_abundances.abundance', 'number of taxon_id', 'single_item', true, NULL, NULL),
            (10, 'taxon_id', 'tbl_abundances', 'tbl_abundances.taxon_id', 'Taxon id  (specie)', 'single_item', true, NULL, NULL),
            (11, 'dataset', 'tbl_datasets', 'tbl_datasets.dataset_name', 'Dataset', 'single_item', true, NULL, NULL),
            (12, 'dataset_link', 'tbl_datasets', 'tbl_datasets.dataset_id', 'Dataset details', 'single_item', true, 'client/show_dataset_details.php?dataset_id', NULL),
            (13, 'dataset_link_filtered', 'tbl_datasets', 'tbl_datasets.dataset_id', 'Filtered report', 'single_item', true, 'client/show_dataset_details.php?dataset_id', NULL),
            (14, 'sample_group', 'tbl_sample_groups', 'tbl_sample_groups.sample_group_name', 'Sample group', 'single_item', true, NULL, NULL),
            (15, 'methods', 'tbl_methods', 'tbl_methods.method_name', 'Method', 'single_item', true, NULL, NULL),
            (18, 'category_id', NULL, 'category_id', 'Site ID', 'single_item', true, NULL, NULL),
            (19, 'category_name', NULL, 'category_name', 'Site Name', 'single_item', true, NULL, NULL),
            (20, 'latitude_dd', NULL, 'latitude_dd', 'Latitude (dd)', 'single_item', true, NULL, NULL),
            (21, 'longitude_dd', NULL, 'longitude_dd', 'Longitude (dd)', 'single_item', true, NULL, NULL)
        ) on conflict (result_field_id) do update
            set result_field_key = excluded.result_field_key,
                table_name = excluded.table_name,
                column_name = excluded.column_name,
                display_text = excluded.display_text,
                field_type_id = excluded.field_type_id,
                activated = excluded.activated,
                link_url = excluded.link_url,
                link_label = excluded.link_label;

       insert into facet.result_aggregate_field (aggregate_field_id, aggregate_id, result_field_id, field_type_id, sequence_id) (values
            (4, 1, 1, 'single_item', 1),
            (5, 1, 2, 'text_agg_item', 2),
            (8, 1, 3, 'count_item', 3),
            (10, 1, 4, 'link_item', 4),
            (16, 1, 5, 'link_item_filtered', 5),
            (13, 1, 1, 'sort_item', 99),
            (15, 2, 6, 'link_item_filtered', 1),
            (7, 2, 3, 'count_item', 2),
            (1, 3, 1, 'single_item', 1),
            (2, 3, 14, 'single_item', 2),
            (3, 3, 2, 'single_item', 3),
            (6, 3, 3, 'count_item', 4),
            (9, 3, 7, 'link_item', 5),
            (14, 3, 8, 'link_item_filtered', 6),
            (11, 3, 1, 'sort_item', 99),
            (12, 3, 14, 'sort_item', 99),
            (23, 4, 18, 'single_item', 1),
            (24, 4, 19, 'single_item', 2),
            (21, 4, 20, 'single_item', 3),
            (22, 4, 21, 'single_item', 4)
        ) on conflict (aggregate_field_id) do update
            set aggregate_id = excluded.aggregate_id,
                result_field_id = excluded.result_field_id,
                field_type_id = excluded.field_type_id,
                sequence_id = excluded.sequence_id;

       insert into facet.result_view_type (view_type_id, view_name, is_cachable) (values
            ('tabular', 'Tabular', true),
            ('map', 'Map', false)
        ) on conflict (view_type_id) do update
            set view_name = excluded.view_name,
                is_cachable = excluded.is_cachable;

        insert into facet.view_state (view_state_key, view_state_data, create_time) (values
            ('roger', 'mähler', '2018-04-24 16:08:45.620597+02'),
            ('humlab', 'roger mähler', '2018-04-24 16:13:07.975984+02')
        ) on conflict do nothing;

    exception when sqlstate 'GUARD' then
        raise notice 'ALREADY EXECUTED';
    end;

end $$;
commit;

