-- Deploy sead_change_control:20231120_DML_DENDRO_DATES_SCHEMA_UPDATE to pg

/****************************************************************************************************************
  Author        Roger Mähler
  Date          2019-01-01
  Description   
  Prerequisites 
  Reviewer      
  Approver      
  Idempotent    Yes
  Notes         This script assumes that all dendro data has been removed from the database.
                This script is a part of the solution to the issue 135.                
  Issue https://github.com/humlab-sead/sead_change_control/issues/135
*****************************************************************************************************************/

begin;
do $$
begin

    begin
    
        next_location_id = 4586

        WITH new_locations(location_id, location_name, location_type_id) AS ( VALUES

INSERT
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4586, 'Västra Götaland', 7);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4587, 'Gotlands län', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4588, 'Östergötlands län', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4589, 'Aneby kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4590, 'Boxholm kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4591, 'Bromölla kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4592, 'Burlöv kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4593, 'Ekerö kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4594, 'Eslöv kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4595, 'Finspång kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4596, 'Flen kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4597, 'Gotland kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4598, 'Göteborg kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4599, 'Heby kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4600, 'Helsingborg kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4601, 'Hässleholm kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4602, 'Höganäs kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4603, 'Höör kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4604, 'Katrineholm kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4605, 'Kinda kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4606, 'Kristianstad kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4607, 'Kävlinge kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4608, 'Linköping kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4609, 'Lund kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4610, 'Mjölby kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4611, 'Motala kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4612, 'Mörbylånga kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4613, 'Nacka kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4614, 'Norrköping kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4615, 'Nässjö kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4616, 'Perstorp kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4617, 'Simrishamn kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4618, 'Sjöbo kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4619, 'Skurup kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4620, 'Sollentuna kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4621, 'Solna kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4622, 'Staffanstorp kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4623, 'Stockholm kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4624, 'Svalöv kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4625, 'Svedala kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4626, 'Söderköping kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4627, 'Södertälje kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4628, 'Tierp kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4629, 'Tomelilla kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4630, 'Torsås kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4631, 'Trelleborg kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4632, 'Trosa kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4633, 'Tyresö kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4634, 'Upplands Väsby kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4635, 'Vadstena kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4636, 'Valdemarsvik kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4637, 'Vallentuna kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4638, 'Vingåker kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4639, 'Värmdö kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4640, 'Ydre kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4641, 'Ystad kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4642, 'Åtvidaberg kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4643, 'Ödeshög kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4644, 'Östhammar kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4645, 'Östra Göinge kommun', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4646, 'Algutsrum socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4647, 'Alseda socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4648, 'Alsike socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4649, 'Alskog socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4650, 'Alva socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4651, 'Arby socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4652, 'Asby socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4653, 'Ask socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4654, 'Baldringe socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4655, 'Balkåkra socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4656, 'Bankekind socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4657, 'Bellö socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4658, 'Bjälbo socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4659, 'Björka socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4660, 'Björnlunda socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4661, 'Bonderup socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4662, 'Boo socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4663, 'Borgholm socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4664, 'Bosebo socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4665, 'Bredsätra socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4666, 'Bromma socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4667, 'Brunnby socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4668, 'Brönnestad socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4669, 'Bunge socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4670, 'Burs socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4671, 'Bäl socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4672, 'Djursdala socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4673, 'Dörby socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4674, 'Ed socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4675, 'Edsbro socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4676, 'Eke socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4677, 'Eksjö socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4678, 'Etelhem socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4679, 'Farhult socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4680, 'Faringe socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4681, 'Farstorp socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4682, 'Film socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4683, 'Fivelstad socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4684, 'Fleringe socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4685, 'Flisby socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4686, 'Flistad socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4687, 'Floda socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4688, 'Follingbo socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4689, 'Forsmark socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4690, 'Frötuna socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4691, 'Furingstad socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4692, 'Färlöv socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4693, 'Gammelgarn socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4694, 'Garde socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4695, 'Genarp socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4696, 'Gillberga socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4697, 'Glimåkra socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4698, 'Glömminge socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4699, 'Gothem socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4700, 'Gryt socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4701, 'Guldrupe socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4702, 'Gullabo socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4703, 'Gårdsby socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4704, 'Gärdslösa socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4705, 'Göteborg socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4706, 'Hagebyhöga socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4707, 'Hall socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4708, 'Halla socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4709, 'Halltorp socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4710, 'Hammarby socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4711, 'Hammarlunda socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4712, 'Heda socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4713, 'Hejde socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4714, 'Hellvi socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4715, 'Hofterup socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4716, 'Holmby socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4717, 'Horn socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4718, 'Hov socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4719, 'Hult socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4720, 'Husby-Sjuhundra socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4721, 'Husby-Ärlinghundra socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4722, 'Hållnäs socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4723, 'Häglinge socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4724, 'Hällestad socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4725, 'Härad socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4726, 'Härlöv socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4727, 'Härnevi socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4728, 'Hässleby socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4729, 'Hörja socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4730, 'Hörsne socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4731, 'Järlåsa socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4732, 'Järsnäs socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4733, 'Jönköping socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4734, 'Kaga socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4735, 'Kisa socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4736, 'Kristianstad socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4737, 'Kristvalla socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4738, 'Kullerstad socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4739, 'Kumla socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4740, 'Kyrkoköpinge socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4741, 'Källunge socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4742, 'Kärnbo socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4743, 'Kävlinge socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4744, 'Landeryd socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4745, 'Lau socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4746, 'Levide socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4747, 'Lilla Harrie socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4748, 'Linde socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4749, 'Linderöd socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4750, 'Linköping socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4751, 'Lojsta socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4752, 'Lovö socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4753, 'Lye socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4754, 'Långlöt socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4755, 'Länna socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4756, 'Lärbro socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4757, 'Löt socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4758, 'Mellösa socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4759, 'Mjölby socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4760, 'Motala socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4761, 'Mörbylånga socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4762, 'Norra Mellby socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4763, 'Norra Rörum socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4764, 'Norra Solberga socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4765, 'Norra Vi socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4766, 'Norrlanda socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4767, 'Norrtälje socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4768, 'Nybro socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4769, 'Nykyrka socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4770, 'Näs socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4771, 'Näshulta socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4772, 'Orkesta socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4773, 'Oskarshamn socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4774, 'Perstorp socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4775, 'Ravlunda socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4776, 'Riala socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4777, 'Risinge socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4778, 'Rogslösa socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4779, 'Roma socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4780, 'Roslags-bro socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4781, 'Runsten socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4782, 'Ryssby socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4783, 'Rö socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4784, 'Sanda socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4785, 'Sandby socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4786, 'Sireköpinge socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4787, 'Sjörup socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4788, 'Skabersjö socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4789, 'Skedevi socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4790, 'Skeppsås socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4791, 'Skånela socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4792, 'Skårby socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4793, 'Skäfthammar socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4794, 'Skönberga socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4795, 'Smedstorp socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4796, 'Sollentuna socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4797, 'Solna socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4798, 'Sorunda socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4799, 'Sproge socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4800, 'Stenkumla socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4801, 'Stockholm socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4802, 'Stora Harrie socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4803, 'Strå socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4804, 'Sundre socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4805, 'Svärta socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4806, 'Särslöv socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4807, 'Söderby karl socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4808, 'Söderbykarl socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4809, 'Södra Möckleby socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4810, 'Tegelsmora socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4811, 'Tidersrum socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4812, 'Tingstäde socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4813, 'Torpa socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4814, 'Torsås socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4815, 'Tosterup socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4816, 'Trehörna socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4817, 'Tryserum socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4818, 'Träne socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4819, 'Tyresö socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4820, 'Ukna socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4821, 'Ulrika socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4822, 'Vadsbro socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4823, 'Vadstena socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4824, 'Vall socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4825, 'Vallentuna socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4826, 'Valö socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4827, 'Vamlingbo socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4828, 'Vassunda socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4829, 'Vickelby socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4830, 'Vickleby socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4831, 'Villie socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4832, 'Vireda socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4833, 'Visseltofta socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4834, 'Voxtorp socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4835, 'Vånga socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4836, 'Våthult socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4837, 'Väddö socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4838, 'Värmdö socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4839, 'Värna socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4840, 'Väsby socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4841, 'Västerlövsta socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4842, 'Västermo socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4843, 'Västra Eneby socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4844, 'Västra Klagstorp socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4845, 'Västra Nöbbelöv socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4846, 'Västra Vingåker socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4847, 'Västra Vram socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4848, 'Väversunda socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4849, 'Ydre socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4850, 'Åsbo socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4851, 'Åtvid socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4852, 'Älvestad socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4853, 'Ör socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4854, 'Örberga socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4855, 'Örsjö socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4856, 'Östergarn socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4857, 'Österåker socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4858, 'Östra Ed socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4859, 'Östra Ryd socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4860, 'Östra Skrukeby socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4861, 'Östra Vingåker socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4862, 'Östra Vram socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4863, 'Överselö socken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4864, 'Alvesta Härlöv', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4865, 'Arby kyrka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4866, 'Asby', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4867, 'Ask', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4868, 'Baldringe', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4869, 'Balkåkra', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4870, 'Bankekinds kyrkojord', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4871, 'Bellö', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4872, 'Bergsjöholm', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4873, 'Billsta', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4874, 'Biskopshuset', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4875, 'Bjälbo', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4876, 'Bjäresjö', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4877, 'Björka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4878, 'Björkenäs', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4879, 'Björklunda', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4880, 'Bonderup', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4881, 'Borntorp', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4882, 'Bosarp', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4883, 'Brahekyrkogården', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4884, 'Bredsätra kyrka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4885, 'Broarp', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4886, 'Bromma', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4887, 'Bruksgatan', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4888, 'Brunnby', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4889, 'Brönnestad', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4890, 'Burlöv', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4891, 'Burmeister', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4892, 'Dalby', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4893, 'Djurgården', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4894, 'Domkyrkan', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4895, 'Drottningholm', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4896, 'Dörby kyrka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4897, 'Ekeberg', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4898, 'Ekeby', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4899, 'Ekelunda', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4900, 'Erikskulle', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4901, 'Eriksöre', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4902, 'Farhult', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4903, 'Finntorp', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4904, 'Fivelstad', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4905, 'Flistad', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4906, 'Friggestad', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4907, 'Furingstad', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4908, 'Fåglarp', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4909, 'Fångö', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4910, 'Färlöv', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4911, 'Föllingsö', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4912, 'Gamla staden', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4913, 'Gamla vägen', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4914, 'Genarp', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4915, 'Gimo', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4916, 'Glimmingehus', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4917, 'Glömminge prästgård', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4918, 'Grisslehamn', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4919, 'Grävsten', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4920, 'Gällstaö Gård', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4921, 'Gärdslösa kyrka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4922, 'Haga', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4923, 'Hagby kyrka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4924, 'Hagebyhöga', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4925, 'Hakarp', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4926, 'Hala', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4927, 'Halltorps kyrka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4928, 'Hammarlunda', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4929, 'Harpsund', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4930, 'Heda', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4931, 'Hedeskoga', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4932, 'Helgelsens gård', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4933, 'Herrestad', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4934, 'Herrökna gård', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4935, 'Hester', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4936, 'Hofterup', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4937, 'Horns kyrka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4938, 'Hossmo kyrka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4939, 'Hov', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4940, 'Hovdala', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4941, 'Hulla', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4942, 'Hulterstads kyrka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4943, 'Hults kulla', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4944, 'Hunnebergsgatan', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4945, 'Husby', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4946, 'Hårsbäck Sör', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4947, 'Häljaryd', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4948, 'Härads kyrkby', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4949, 'Härnevi', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4950, 'Häverö prästgård', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4951, 'Hävla', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4952, 'Högsjö gård', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4953, 'Hönstorp', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4954, 'Hörja', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4955, 'Ilnestorp', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4956, 'Ingatorp', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4957, 'Innerstaden', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4958, 'Juteboda', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4959, 'Kaga', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4960, 'Kalmar Voxtorps kyrka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4961, 'Karkebo', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4962, 'Klagstorp', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4963, 'Klosterkyrkan', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4964, 'Kolberga', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4965, 'Kolstad', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4966, 'Krapperup', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4967, 'Krogsfall', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4968, 'Krusenberg', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4969, 'Kråkvik', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4970, 'Kullerstad', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4971, 'Kulltorp', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4972, 'Kumla kyrka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4973, 'Kumlabykyrkogården', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4974, 'Kummelnäs gård', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4975, 'Kvarteret Allön', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4976, 'Kvarteret Almen', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4977, 'Kvarteret Ankaret', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4978, 'Kvarteret Apoteket', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4979, 'Kvarteret Bokbindaren', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4980, 'Kvarteret Boktryckaren', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4981, 'Kvarteret Borgmästaren', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4982, 'Kvarteret Båtsmannen', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4983, 'Kvarteret Ciselören', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4984, 'Kvarteret Fältskären', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4985, 'Kvarteret Färgaren', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4986, 'Kvarteret Garvaren', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4987, 'Kvarteret Gråmunkeholmen', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4988, 'Kvarteret Guldsmeden', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4989, 'Kvarteret Hattmakaren', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4990, 'Kvarteret Innerstaden', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4991, 'Kvarteret Kaplanen', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4992, 'Kvarteret Kassamannen', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4993, 'Kvarteret Kommendanten', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4994, 'Kvarteret Komministern', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4995, 'Kvarteret Kopparslagaren ', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4996, 'Kvarteret Krögaren', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4997, 'Kvarteret Laboratorn', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4998, 'Kvarteret Museet', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (4999, 'Kvarteret Norge', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5000, 'Kvarteret Novisen', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5001, 'Kvarteret Ormen', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5002, 'Kvarteret Orren', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5003, 'Kvarteret Prelaten', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5004, 'Kvarteret Priorn', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5005, 'Kvarteret Repslagaren', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5006, 'Kvarteret Rådhuset', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5007, 'Kvarteret Skonaren', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5008, 'Kvarteret Specksrum', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5009, 'Kvarteret Svartbrodern', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5010, 'Kvarteret Vaxblekaren', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5011, 'Kvarteret Vinskänken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5012, 'Kvarteret Östergötland', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5013, 'Kvilla', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5014, 'Kyrkogården', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5015, 'Kävlinge', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5016, 'Köpinge', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5017, 'Landsnora kvarn', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5018, 'Lilla Björkudden', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5019, 'Lilla Rotsunda', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5020, 'Linderöd', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5021, 'Lohärads Prästgård', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5022, 'Lopperstad', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5023, 'Långlöts kyrka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5024, 'Löddeköpinge', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5025, 'Lögla', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5026, 'Löt', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5027, 'Lövö', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5028, 'Malmstorp', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5029, 'Mariannelund', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5030, 'Marsjö', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5031, 'Masten', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5032, 'Mellanköpinge', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5033, 'Mellby', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5034, 'Mortorps kyrka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5035, 'Mörbylånga kyrka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5036, 'Noors Herrgård', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5037, 'Nora Prästgård', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5038, 'Norra Rörum', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5039, 'Norra Åsum', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5040, 'Norrvidinge', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5041, 'Nykyrka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5042, 'Näs', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5043, 'Nöbbelöv', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5044, 'Onkel Adamsgården', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5045, 'Orkestaby', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5046, 'Ottenby', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5047, 'Perstorp', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5048, 'Prästgården', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5049, 'Prästtorp', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5050, 'Qvarnarp', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5051, 'Ravlunda', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5052, 'Resmo kyrka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5053, 'Rogslösa', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5054, 'Roma kloster', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5055, 'Rundelsgränd', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5056, 'Rydboholm', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5057, 'Ryssby kyrka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5058, 'Ryssebo', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5059, 'Salvarp', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5060, 'Sandby', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5061, 'Sandemar', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5062, 'Sankta Maria', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5063, 'Sjörup', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5064, 'Skedshult', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5065, 'Skeppsås', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5066, 'Skrickerum', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5067, 'Skrukeby', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5068, 'Skålsta', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5069, 'Skånsta', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5070, 'Skårby', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5071, 'Sköldsborg', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5072, 'Skönberga prästgård', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5073, 'Slattefors', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5074, 'Slevringe', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5075, 'Slottsfogden', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5076, 'Slottsskogen', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5077, 'Slättåkra', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5078, 'Sonnorp', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5079, 'Specksrum', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5080, 'Stallbacksvägen 8', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5081, 'Steninge', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5082, 'Stockholms Slott', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5083, 'Stora Harrie', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5084, 'Stora Hulterska', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5085, 'Strandskogen', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5086, 'Stångsmåla', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5087, 'Stämmeryd', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5088, 'Svaneberg', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5089, 'Särslöv', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5090, 'Sättra', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5091, 'Södra Möckleby kyrka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5092, 'Tidersrum', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5093, 'Tingshustorget', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5094, 'Tofta', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5095, 'Torhult', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5096, 'Torpa', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5097, 'Torö kyrka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5098, 'Trehörna', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5099, 'Träne', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5100, 'Tumbo Prästgård', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5101, 'Tvartorp', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5102, 'Tyresö', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5103, 'Tångerda', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5104, 'Törnbotten', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5105, 'Uggelbo', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5106, 'Ulrika', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5107, 'Ulriksdal', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5108, 'Vadsbroby', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5109, 'Vallsnäs', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5110, 'Vanserum', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5111, 'Verksgatan', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5112, 'Viby gård', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5113, 'Vickleby kyrka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5114, 'Viggeby', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5115, 'Villie', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5116, 'Vingåker-Kvarngölet', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5117, 'Vippröste', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5118, 'Vireda', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5119, 'Visseltofta', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5120, 'Våthult', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5121, 'Vänge-Ekeby', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5122, 'Värdshusbacken', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5123, 'Värmdö kyrka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5124, 'Väsby', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5125, 'Väsby kvarn', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5126, 'Väster Lakbäck', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5127, 'Västermo kyrka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5128, 'Västra Häglinge', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5129, 'Väversunda', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5130, 'Växjö Ör', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5131, 'Ydre Vi-Smedstorp', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5132, 'Åby', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5133, 'Åkarp', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5134, 'Åsby', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5135, 'Åtvidaberg kyrkeby', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5136, 'Älvestad', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5137, 'Ängstigen', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5138, 'Öndal', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5139, 'Örberga', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5140, 'Östra Vram', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5141, 'Östrabo', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5142, 'Överby kvarn', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5143, 'Överselö kyrka', 2);
INSERT INTO tbl_locations (location_id, location_name, location_type_id) VALUES (5144, 'Övraby', 2);


    exception when sqlstate 'GUARD' then
        raise notice 'ALREADY EXECUTED';
    end;
    
end $$;
commit;
